#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace SmartEP.DomainModel	
{
	public partial class Frame_UserEntity
	{
		private int m_iD;
		public virtual int ID
		{
			get
			{
				return this.m_iD;
			}
			set
			{
				this.m_iD = value;
			}
		}
		
		private string m_rowGuid;
		public virtual string RowGuid
		{
			get
			{
				return this.m_rowGuid;
			}
			set
			{
				this.m_rowGuid = value;
			}
		}
		
		private string m_orgGuid;
		public virtual string OrgGuid
		{
			get
			{
				return this.m_orgGuid;
			}
			set
			{
				this.m_orgGuid = value;
			}
		}
		
		private string m_deptGuid;
		public virtual string DeptGuid
		{
			get
			{
				return this.m_deptGuid;
			}
			set
			{
				this.m_deptGuid = value;
			}
		}
		
		private string m_loginID;
		public virtual string LoginID
		{
			get
			{
				return this.m_loginID;
			}
			set
			{
				this.m_loginID = value;
			}
		}
		
		private string m_password;
		public virtual string Password
		{
			get
			{
				return this.m_password;
			}
			set
			{
				this.m_password = value;
			}
		}
		
		private string m_displayName;
		public virtual string DisplayName
		{
			get
			{
				return this.m_displayName;
			}
			set
			{
				this.m_displayName = value;
			}
		}
		
		private string m_empGuid;
		public virtual string EmpGuid
		{
			get
			{
				return this.m_empGuid;
			}
			set
			{
				this.m_empGuid = value;
			}
		}
		
		private string m_theme;
		public virtual string Theme
		{
			get
			{
				return this.m_theme;
			}
			set
			{
				this.m_theme = value;
			}
		}
		
		private string m_navigationType;
		public virtual string NavigationType
		{
			get
			{
				return this.m_navigationType;
			}
			set
			{
				this.m_navigationType = value;
			}
		}
		
		private string m_defaultMenuType;
		public virtual string DefaultMenuType
		{
			get
			{
				return this.m_defaultMenuType;
			}
			set
			{
				this.m_defaultMenuType = value;
			}
		}
		
		private string m_hardwareKey;
		public virtual string HardwareKey
		{
			get
			{
				return this.m_hardwareKey;
			}
			set
			{
				this.m_hardwareKey = value;
			}
		}
		
		private int? m_sortNumber;
		public virtual int? SortNumber
		{
			get
			{
				return this.m_sortNumber;
			}
			set
			{
				this.m_sortNumber = value;
			}
		}
		
		private int? m_isEnabled;
		public virtual int? IsEnabled
		{
			get
			{
				return this.m_isEnabled;
			}
			set
			{
				this.m_isEnabled = value;
			}
		}
		
		private string m_remark;
		public virtual string Remark
		{
			get
			{
				return this.m_remark;
			}
			set
			{
				this.m_remark = value;
			}
		}
		
		private int? m_sex;
		public virtual int? Sex
		{
			get
			{
				return this.m_sex;
			}
			set
			{
				this.m_sex = value;
			}
		}
		
		private string m_mobile;
		public virtual string Mobile
		{
			get
			{
				return this.m_mobile;
			}
			set
			{
				this.m_mobile = value;
			}
		}
		
	}
}
#pragma warning restore 1591
