#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.AirMonitoringBusiness;

namespace SmartEP.DomainModel.AirMonitoringBusiness	
{
	public partial class AQIForcastEntity : IAirMonitoringBusinessEntityProperty
	{
		private string m_aQIForcastUid;
		public virtual string AQIForcastUid
		{
			get
			{
				return this.m_aQIForcastUid;
			}
			set
			{
				this.m_aQIForcastUid = value;
			}
		}
		
		private DateTime? m_reportDateTime;
		public virtual DateTime? ReportDateTime
		{
			get
			{
				return this.m_reportDateTime;
			}
			set
			{
				this.m_reportDateTime = value;
			}
		}
		
		private string m_yesterdayAQI;
		public virtual string YesterdayAQI
		{
			get
			{
				return this.m_yesterdayAQI;
			}
			set
			{
				this.m_yesterdayAQI = value;
			}
		}
		
		private string m_yesterdayPrimaryPollutant;
		public virtual string YesterdayPrimaryPollutant
		{
			get
			{
				return this.m_yesterdayPrimaryPollutant;
			}
			set
			{
				this.m_yesterdayPrimaryPollutant = value;
			}
		}
		
		private string m_yesterdayClass;
		public virtual string YesterdayClass
		{
			get
			{
				return this.m_yesterdayClass;
			}
			set
			{
				this.m_yesterdayClass = value;
			}
		}
		
		private int? m_todayAQIMax;
		public virtual int? TodayAQIMax
		{
			get
			{
				return this.m_todayAQIMax;
			}
			set
			{
				this.m_todayAQIMax = value;
			}
		}
		
		private int? m_todayAQIMin;
		public virtual int? TodayAQIMin
		{
			get
			{
				return this.m_todayAQIMin;
			}
			set
			{
				this.m_todayAQIMin = value;
			}
		}
		
		private string m_todayPrimarilyPollutant;
		public virtual string TodayPrimarilyPollutant
		{
			get
			{
				return this.m_todayPrimarilyPollutant;
			}
			set
			{
				this.m_todayPrimarilyPollutant = value;
			}
		}
		
		private string m_todayAirQuality;
		public virtual string TodayAirQuality
		{
			get
			{
				return this.m_todayAirQuality;
			}
			set
			{
				this.m_todayAirQuality = value;
			}
		}
		
		private string m_tomorrowAirQuality;
		public virtual string TomorrowAirQuality
		{
			get
			{
				return this.m_tomorrowAirQuality;
			}
			set
			{
				this.m_tomorrowAirQuality = value;
			}
		}
		
		private string m_tomorrowTakeStep;
		public virtual string TomorrowTakeStep
		{
			get
			{
				return this.m_tomorrowTakeStep;
			}
			set
			{
				this.m_tomorrowTakeStep = value;
			}
		}
		
		private string m_issuedUnit;
		public virtual string IssuedUnit
		{
			get
			{
				return this.m_issuedUnit;
			}
			set
			{
				this.m_issuedUnit = value;
			}
		}
		
		private DateTime? m_issuedDateTime;
		public virtual DateTime? IssuedDateTime
		{
			get
			{
				return this.m_issuedDateTime;
			}
			set
			{
				this.m_issuedDateTime = value;
			}
		}
		
		private bool? m_isIssuedOrNot;
		public virtual bool? IsIssuedOrNot
		{
			get
			{
				return this.m_isIssuedOrNot;
			}
			set
			{
				this.m_isIssuedOrNot = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private IList<AQIForcastDescEntity> m_aQIForcastDescEntities = new List<AQIForcastDescEntity>();
		public virtual IList<AQIForcastDescEntity> AQIForcastDescEntities
		{
			get
			{
				return this.m_aQIForcastDescEntities;
			}
		}
		
	}
}
#pragma warning restore 1591
