#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace SmartEP.DomainModel.MonitoringBusiness	
{
	public partial class DataOnlineEntity
	{
		private int m_id;
		public virtual int Id
		{
			get
			{
				return this.m_id;
			}
			set
			{
				this.m_id = value;
			}
		}
		
		private string m_applicationUid;
		public virtual string ApplicationUid
		{
			get
			{
				return this.m_applicationUid;
			}
			set
			{
				this.m_applicationUid = value;
			}
		}
		
		private string m_monitoringPointUid;
		public virtual string MonitoringPointUid
		{
			get
			{
				return this.m_monitoringPointUid;
			}
			set
			{
				this.m_monitoringPointUid = value;
			}
		}
		
		private int? m_pointId;
		public virtual int? PointId
		{
			get
			{
				return this.m_pointId;
			}
			set
			{
				this.m_pointId = value;
			}
		}
		
		private string m_dataTypeUid;
		public virtual string DataTypeUid
		{
			get
			{
				return this.m_dataTypeUid;
			}
			set
			{
				this.m_dataTypeUid = value;
			}
		}
		
		private int? m_isOnline;
		public virtual int? IsOnline
		{
			get
			{
				return this.m_isOnline;
			}
			set
			{
				this.m_isOnline = value;
			}
		}
		
		private DateTime? m_newDataTime;
		public virtual DateTime? NewDataTime
		{
			get
			{
				return this.m_newDataTime;
			}
			set
			{
				this.m_newDataTime = value;
			}
		}
		
		private int? m_offLineTime;
		public virtual int? OffLineTime
		{
			get
			{
				return this.m_offLineTime;
			}
			set
			{
				this.m_offLineTime = value;
			}
		}
		
		private int? m_recent24HourRecords;
		public virtual int? Recent24HourRecords
		{
			get
			{
				return this.m_recent24HourRecords;
			}
			set
			{
				this.m_recent24HourRecords = value;
			}
		}
		
	}
}
#pragma warning restore 1591
