#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.BaseData;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class PollutantCodeEntity : IStandardEntityProperty
	{
		private string m_pollutantUid;
		public virtual string PollutantUid
		{
			get
			{
				return this.m_pollutantUid;
			}
			set
			{
				this.m_pollutantUid = value;
			}
		}
		
		private string m_pollutantTypeUid;
		public virtual string PollutantTypeUid
		{
			get
			{
				return this.m_pollutantTypeUid;
			}
			set
			{
				this.m_pollutantTypeUid = value;
			}
		}
		
		private string m_pollutantCode;
		public virtual string PollutantCode
		{
			get
			{
				return this.m_pollutantCode;
			}
			set
			{
				this.m_pollutantCode = value;
			}
		}
		
		private string m_gBCode;
		public virtual string GBCode
		{
			get
			{
				return this.m_gBCode;
			}
			set
			{
				this.m_gBCode = value;
			}
		}
		
		private string m_pollutantName;
		public virtual string PollutantName
		{
			get
			{
				return this.m_pollutantName;
			}
			set
			{
				this.m_pollutantName = value;
			}
		}
		
		private string m_shortName;
		public virtual string ShortName
		{
			get
			{
				return this.m_shortName;
			}
			set
			{
				this.m_shortName = value;
			}
		}
		
		private string m_englishName;
		public virtual string EnglishName
		{
			get
			{
				return this.m_englishName;
			}
			set
			{
				this.m_englishName = value;
			}
		}
		
		private string m_chemicalSymbol;
		public virtual string ChemicalSymbol
		{
			get
			{
				return this.m_chemicalSymbol;
			}
			set
			{
				this.m_chemicalSymbol = value;
			}
		}
		
		private string m_cASNumber;
		public virtual string CASNumber
		{
			get
			{
				return this.m_cASNumber;
			}
			set
			{
				this.m_cASNumber = value;
			}
		}
		
		private string m_shortNameHTML;
		public virtual string ShortNameHTML
		{
			get
			{
				return this.m_shortNameHTML;
			}
			set
			{
				this.m_shortNameHTML = value;
			}
		}
		
		private string m_fullNameHTML;
		public virtual string FullNameHTML
		{
			get
			{
				return this.m_fullNameHTML;
			}
			set
			{
				this.m_fullNameHTML = value;
			}
		}
		
		private string m_measureUnitUid;
		public virtual string MeasureUnitUid
		{
			get
			{
				return this.m_measureUnitUid;
			}
			set
			{
				this.m_measureUnitUid = value;
			}
		}
		
		private int? m_decimalDigit;
		public virtual int? DecimalDigit
		{
			get
			{
				return this.m_decimalDigit;
			}
			set
			{
				this.m_decimalDigit = value;
			}
		}
		
		private string m_indicatorUid;
		public virtual string IndicatorUid
		{
			get
			{
				return this.m_indicatorUid;
			}
			set
			{
				this.m_indicatorUid = value;
			}
		}
		
		private string m_categoryUid;
		public virtual string CategoryUid
		{
			get
			{
				return this.m_categoryUid;
			}
			set
			{
				this.m_categoryUid = value;
			}
		}
		
		private string m_typeUid;
		public virtual string TypeUid
		{
			get
			{
				return this.m_typeUid;
			}
			set
			{
				this.m_typeUid = value;
			}
		}
		
		private string m_sourceTypeUid;
		public virtual string SourceTypeUid
		{
			get
			{
				return this.m_sourceTypeUid;
			}
			set
			{
				this.m_sourceTypeUid = value;
			}
		}
		
		private bool? m_isUseOrNot;
		public virtual bool? IsUseOrNot
		{
			get
			{
				return this.m_isUseOrNot;
			}
			set
			{
				this.m_isUseOrNot = value;
			}
		}
		
		private bool? m_isCalEQIOrNot;
		public virtual bool? IsCalEQIOrNot
		{
			get
			{
				return this.m_isCalEQIOrNot;
			}
			set
			{
				this.m_isCalEQIOrNot = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private string m_rowStatus;
		public virtual string RowStatus
		{
			get
			{
				return this.m_rowStatus;
			}
			set
			{
				this.m_rowStatus = value;
			}
		}
		
		private string m_rowGuid;
		public virtual string RowGuid
		{
			get
			{
				return this.m_rowGuid;
			}
			set
			{
				this.m_rowGuid = value;
			}
		}
		
		private int m_id;
		public virtual int Id
		{
			get
			{
				return this.m_id;
			}
			set
			{
				this.m_id = value;
			}
		}
		
		private string m_addUserName;
		public virtual string AddUserName
		{
			get
			{
				return this.m_addUserName;
			}
			set
			{
				this.m_addUserName = value;
			}
		}
		
		private string m_addUserGuid;
		public virtual string AddUserGuid
		{
			get
			{
				return this.m_addUserGuid;
			}
			set
			{
				this.m_addUserGuid = value;
			}
		}
		
		private string m_addOUName;
		public virtual string AddOUName
		{
			get
			{
				return this.m_addOUName;
			}
			set
			{
				this.m_addOUName = value;
			}
		}
		
		private string m_addOUGuid;
		public virtual string AddOUGuid
		{
			get
			{
				return this.m_addOUGuid;
			}
			set
			{
				this.m_addOUGuid = value;
			}
		}
		
		private DateTime? m_addDate;
		public virtual DateTime? AddDate
		{
			get
			{
				return this.m_addDate;
			}
			set
			{
				this.m_addDate = value;
			}
		}
		
		private bool? m_isQCOrNot;
		public virtual bool? IsQCOrNot
		{
			get
			{
				return this.m_isQCOrNot;
			}
			set
			{
				this.m_isQCOrNot = value;
			}
		}
		
		private int? m_qCOrderNum;
		public virtual int? QCOrderNum
		{
			get
			{
				return this.m_qCOrderNum;
			}
			set
			{
				this.m_qCOrderNum = value;
			}
		}
		
	}
}
#pragma warning restore 1591
