#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace BaseDataModel	
{
	public partial class Instrument_OnlineSetting
	{
		private int _id;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _rowGuid;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		[System.ComponentModel.DataAnnotations.Required()]
		[System.ComponentModel.DataAnnotations.Key()]
		public virtual string RowGuid
		{
			get
			{
				return this._rowGuid;
			}
			set
			{
				this._rowGuid = value;
			}
		}
		
		private string _instrumentUid;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		public virtual string InstrumentUid
		{
			get
			{
				return this._instrumentUid;
			}
			set
			{
				this._instrumentUid = value;
			}
		}
		
		private string _dataTypeUid;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		public virtual string DataTypeUid
		{
			get
			{
				return this._dataTypeUid;
			}
			set
			{
				this._dataTypeUid = value;
			}
		}
		
		private int? _offLineTimeSpan;
		public virtual int? OffLineTimeSpan
		{
			get
			{
				return this._offLineTimeSpan;
			}
			set
			{
				this._offLineTimeSpan = value;
			}
		}
		
		private bool? _enableOrNot;
		public virtual bool? EnableOrNot
		{
			get
			{
				return this._enableOrNot;
			}
			set
			{
				this._enableOrNot = value;
			}
		}
		
		private int? _orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this._orderByNum;
			}
			set
			{
				this._orderByNum = value;
			}
		}
		
		private string _description;
		[System.ComponentModel.DataAnnotations.StringLength(500)]
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private string _creatUser;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		public virtual string CreatUser
		{
			get
			{
				return this._creatUser;
			}
			set
			{
				this._creatUser = value;
			}
		}
		
		private DateTime? _creatDateTime;
		[System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this._creatDateTime;
			}
			set
			{
				this._creatDateTime = value;
			}
		}
		
		private string _updateUser;
		[System.ComponentModel.DataAnnotations.StringLength(10)]
		public virtual string UpdateUser
		{
			get
			{
				return this._updateUser;
			}
			set
			{
				this._updateUser = value;
			}
		}
		
		private DateTime? _updateDateTime;
		[System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this._updateDateTime;
			}
			set
			{
				this._updateDateTime = value;
			}
		}
		
		private string _rowStatus;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		public virtual string RowStatus
		{
			get
			{
				return this._rowStatus;
			}
			set
			{
				this._rowStatus = value;
			}
		}
		
	}
}
#pragma warning restore 1591
