#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.BaseData;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class MonitoringPointEntity : IMPInfoEntityProperty
	{
		private string m_monitoringPointUid;
		public virtual string MonitoringPointUid
		{
			get
			{
				return this.m_monitoringPointUid;
			}
			set
			{
				this.m_monitoringPointUid = value;
			}
		}
		
		private int m_pointId;
		public virtual int PointId
		{
			get
			{
				return this.m_pointId;
			}
		}
		
		private string m_applicationUid;
		public virtual string ApplicationUid
		{
			get
			{
				return this.m_applicationUid;
			}
			set
			{
				this.m_applicationUid = value;
			}
		}
		
		private string m_stationUid;
		public virtual string StationUid
		{
			get
			{
				return this.m_stationUid;
			}
			set
			{
				this.m_stationUid = value;
			}
		}
		
		private string m_monitoringPointName;
		public virtual string MonitoringPointName
		{
			get
			{
				return this.m_monitoringPointName;
			}
			set
			{
				this.m_monitoringPointName = value;
			}
		}
		
		private string m_address;
		public virtual string Address
		{
			get
			{
				return this.m_address;
			}
			set
			{
				this.m_address = value;
			}
		}
		
		private string m_regionUid;
		public virtual string RegionUid
		{
			get
			{
				return this.m_regionUid;
			}
			set
			{
				this.m_regionUid = value;
			}
		}
		
		private string m_monitoringRegionUid;
		public virtual string MonitoringRegionUid
		{
			get
			{
				return this.m_monitoringRegionUid;
			}
			set
			{
				this.m_monitoringRegionUid = value;
			}
		}
		
		private string m_attachmentUid;
		public virtual string AttachmentUid
		{
			get
			{
				return this.m_attachmentUid;
			}
			set
			{
				this.m_attachmentUid = value;
			}
		}
		
		private decimal? m_x;
		public virtual decimal? X
		{
			get
			{
				return this.m_x;
			}
			set
			{
				this.m_x = value;
			}
		}
		
		private decimal? m_y;
		public virtual decimal? Y
		{
			get
			{
				return this.m_y;
			}
			set
			{
				this.m_y = value;
			}
		}
		
		private DateTime? m_buildTime;
		public virtual DateTime? BuildTime
		{
			get
			{
				return this.m_buildTime;
			}
			set
			{
				this.m_buildTime = value;
			}
		}
		
		private string m_instrumentIntegratorUid;
		public virtual string InstrumentIntegratorUid
		{
			get
			{
				return this.m_instrumentIntegratorUid;
			}
			set
			{
				this.m_instrumentIntegratorUid = value;
			}
		}
		
		private string m_monitoringBussinessUid;
		public virtual string MonitoringBussinessUid
		{
			get
			{
				return this.m_monitoringBussinessUid;
			}
			set
			{
				this.m_monitoringBussinessUid = value;
			}
		}
		
		private string m_enviromentFunctionUid;
		public virtual string EnviromentFunctionUid
		{
			get
			{
				return this.m_enviromentFunctionUid;
			}
			set
			{
				this.m_enviromentFunctionUid = value;
			}
		}
		
		private string m_contrlUid;
		public virtual string ContrlUid
		{
			get
			{
				return this.m_contrlUid;
			}
			set
			{
				this.m_contrlUid = value;
			}
		}
		
		private string m_siteTypeUid;
		public virtual string SiteTypeUid
		{
			get
			{
				return this.m_siteTypeUid;
			}
			set
			{
				this.m_siteTypeUid = value;
			}
		}
		
		private string m_runStatusUid;
		public virtual string RunStatusUid
		{
			get
			{
				return this.m_runStatusUid;
			}
			set
			{
				this.m_runStatusUid = value;
			}
		}
		
		private bool? m_isReferencePoint;
		public virtual bool? IsReferencePoint
		{
			get
			{
				return this.m_isReferencePoint;
			}
			set
			{
				this.m_isReferencePoint = value;
			}
		}
		
		private bool? m_showOrNot;
		public virtual bool? ShowOrNot
		{
			get
			{
				return this.m_showOrNot;
			}
			set
			{
				this.m_showOrNot = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private bool? m_enableOrNot;
		public virtual bool? EnableOrNot
		{
			get
			{
				return this.m_enableOrNot;
			}
			set
			{
				this.m_enableOrNot = value;
			}
		}
		
		private string m_operatorsUid;
		public virtual string OperatorsUid
		{
			get
			{
				return this.m_operatorsUid;
			}
			set
			{
				this.m_operatorsUid = value;
			}
		}

        private decimal? m_baiduX;
        public virtual decimal? BaiduX
        {
            get
            {
                return this.m_baiduX;
            }
            set
            {
                this.m_baiduX = value;
            }
        }

        private decimal? m_baiduY;
        public virtual decimal? BaiduY
        {
            get
            {
                return this.m_baiduY;
            }
            set
            {
                this.m_baiduY = value;
            }
        }

		private MonitoringPointExtensionForEQMSWaterEntity m_monitoringPointExtensionForEQMSWaterEntity;
		public virtual MonitoringPointExtensionForEQMSWaterEntity MonitoringPointExtensionForEQMSWaterEntity
		{
			get
			{
				return this.m_monitoringPointExtensionForEQMSWaterEntity;
			}
			set
			{
				this.m_monitoringPointExtensionForEQMSWaterEntity = value;
			}
		}
		
		private MonitoringPointExtensionForEQMSAirEntity m_monitoringPointExtensionForEQMSAirEntity;
		public virtual MonitoringPointExtensionForEQMSAirEntity MonitoringPointExtensionForEQMSAirEntity
		{
			get
			{
				return this.m_monitoringPointExtensionForEQMSAirEntity;
			}
			set
			{
				this.m_monitoringPointExtensionForEQMSAirEntity = value;
			}
		}
		
	}
}
#pragma warning restore 1591
