#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.MonitoringBusiness;

namespace SmartEP.DomainModel.MonitoringBusiness	
{
	public partial class AutoMonitoringMonthSummaryEntity : IMonitoringBusinessEntityProperty
	{
		private string m_recordGuid;
		public virtual string RecordGuid
		{
			get
			{
				return this.m_recordGuid;
			}
			set
			{
				this.m_recordGuid = value;
			}
		}
		
		private DateTime? m_tstamp;
		public virtual DateTime? Tstamp
		{
			get
			{
				return this.m_tstamp;
			}
			set
			{
				this.m_tstamp = value;
			}
		}
		
		private DateTime? m_beginTime;
		public virtual DateTime? BeginTime
		{
			get
			{
				return this.m_beginTime;
			}
			set
			{
				this.m_beginTime = value;
			}
		}
		
		private string m_timeWord;
		public virtual string TimeWord
		{
			get
			{
				return this.m_timeWord;
			}
			set
			{
				this.m_timeWord = value;
			}
		}
		
		private string m_word1;
		public virtual string Word1
		{
			get
			{
				return this.m_word1;
			}
			set
			{
				this.m_word1 = value;
			}
		}
		
		private string m_word2;
		public virtual string Word2
		{
			get
			{
				return this.m_word2;
			}
			set
			{
				this.m_word2 = value;
			}
		}
		
		private string m_word3;
		public virtual string Word3
		{
			get
			{
				return this.m_word3;
			}
			set
			{
				this.m_word3 = value;
			}
		}
		
		private string m_word4;
		public virtual string Word4
		{
			get
			{
				return this.m_word4;
			}
			set
			{
				this.m_word4 = value;
			}
		}
		
		private string m_word5;
		public virtual string Word5
		{
			get
			{
				return this.m_word5;
			}
			set
			{
				this.m_word5 = value;
			}
		}
		
		private string m_word6;
		public virtual string Word6
		{
			get
			{
				return this.m_word6;
			}
			set
			{
				this.m_word6 = value;
			}
		}
		
		private string m_word7;
		public virtual string Word7
		{
			get
			{
				return this.m_word7;
			}
			set
			{
				this.m_word7 = value;
			}
		}
		
		private string m_word8;
		public virtual string Word8
		{
			get
			{
				return this.m_word8;
			}
			set
			{
				this.m_word8 = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private string m_pointNames;
		public virtual string PointNames
		{
			get
			{
				return this.m_pointNames;
			}
			set
			{
				this.m_pointNames = value;
			}
		}
		
		private string m_pointIds;
		public virtual string PointIds
		{
			get
			{
				return this.m_pointIds;
			}
			set
			{
				this.m_pointIds = value;
			}
		}
		
	}
}
#pragma warning restore 1591
