#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.MonitoringBusiness;

namespace SmartEP.DomainModel.MonitoringBusiness	
{
	public partial class BlueAlgaeEarlyWarningMonitoringEntity : IMonitoringBusinessEntityProperty
	{
		private string m_recordGuid;
		public virtual string RecordGuid
		{
			get
			{
				return this.m_recordGuid;
			}
			set
			{
				this.m_recordGuid = value;
			}
		}
		
		private DateTime? m_reportDate;
		public virtual DateTime? ReportDate
		{
			get
			{
				return this.m_reportDate;
			}
			set
			{
				this.m_reportDate = value;
			}
		}
		
		private int? m_reportYear;
		public virtual int? ReportYear
		{
			get
			{
				return this.m_reportYear;
			}
			set
			{
				this.m_reportYear = value;
			}
		}
		
		private int? m_reportPeriods;
		public virtual int? ReportPeriods
		{
			get
			{
				return this.m_reportPeriods;
			}
			set
			{
				this.m_reportPeriods = value;
			}
		}
		
		private int? m_totalPeriods;
		public virtual int? TotalPeriods
		{
			get
			{
				return this.m_totalPeriods;
			}
			set
			{
				this.m_totalPeriods = value;
			}
		}
		
		private string m_drinkingWaterResultTable;
		public virtual string DrinkingWaterResultTable
		{
			get
			{
				return this.m_drinkingWaterResultTable;
			}
			set
			{
				this.m_drinkingWaterResultTable = value;
			}
		}
		
		private string m_drinkingWaterSituation;
		public virtual string DrinkingWaterSituation
		{
			get
			{
				return this.m_drinkingWaterSituation;
			}
			set
			{
				this.m_drinkingWaterSituation = value;
			}
		}
		
		private string m_algaePatrolSituation;
		public virtual string AlgaePatrolSituation
		{
			get
			{
				return this.m_algaePatrolSituation;
			}
			set
			{
				this.m_algaePatrolSituation = value;
			}
		}
		
		private string m_algaePatrolTalbe;
		public virtual string AlgaePatrolTalbe
		{
			get
			{
				return this.m_algaePatrolTalbe;
			}
			set
			{
				this.m_algaePatrolTalbe = value;
			}
		}
		
		private string m_algaeDayDensityTable;
		public virtual string AlgaeDayDensityTable
		{
			get
			{
				return this.m_algaeDayDensityTable;
			}
			set
			{
				this.m_algaeDayDensityTable = value;
			}
		}
		
		private string m_algaeVideoSituation;
		public virtual string AlgaeVideoSituation
		{
			get
			{
				return this.m_algaeVideoSituation;
			}
			set
			{
				this.m_algaeVideoSituation = value;
			}
		}
		
		private string m_algaeVideoImageName;
		public virtual string AlgaeVideoImageName
		{
			get
			{
				return this.m_algaeVideoImageName;
			}
			set
			{
				this.m_algaeVideoImageName = value;
			}
		}
		
		private string m_algaeVideoImageDescription;
		public virtual string AlgaeVideoImageDescription
		{
			get
			{
				return this.m_algaeVideoImageDescription;
			}
			set
			{
				this.m_algaeVideoImageDescription = value;
			}
		}
		
		private string m_remoteSensingMonitoring;
		public virtual string RemoteSensingMonitoring
		{
			get
			{
				return this.m_remoteSensingMonitoring;
			}
			set
			{
				this.m_remoteSensingMonitoring = value;
			}
		}
		
		private string m_remoteSensingImageName1;
		public virtual string RemoteSensingImageName1
		{
			get
			{
				return this.m_remoteSensingImageName1;
			}
			set
			{
				this.m_remoteSensingImageName1 = value;
			}
		}
		
		private string m_remoteSensingImageDescription1;
		public virtual string RemoteSensingImageDescription1
		{
			get
			{
				return this.m_remoteSensingImageDescription1;
			}
			set
			{
				this.m_remoteSensingImageDescription1 = value;
			}
		}
		
		private string m_remoteSensingImageName2;
		public virtual string RemoteSensingImageName2
		{
			get
			{
				return this.m_remoteSensingImageName2;
			}
			set
			{
				this.m_remoteSensingImageName2 = value;
			}
		}
		
		private string m_remoteSensingImageDescription2;
		public virtual string RemoteSensingImageDescription2
		{
			get
			{
				return this.m_remoteSensingImageDescription2;
			}
			set
			{
				this.m_remoteSensingImageDescription2 = value;
			}
		}
		
		private string m_mainlyIntoRiverSituation;
		public virtual string MainlyIntoRiverSituation
		{
			get
			{
				return this.m_mainlyIntoRiverSituation;
			}
			set
			{
				this.m_mainlyIntoRiverSituation = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
	}
}
#pragma warning restore 1591
