#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.MonitoringBusiness;

namespace SmartEP.DomainModel.MonitoringBusiness	
{
	public partial class RealSampleEntity : IMonitoringBusinessEntityProperty
	{
		private string m_compareItem;
		public virtual string CompareItem
		{
			get
			{
				return this.m_compareItem;
			}
			set
			{
				this.m_compareItem = value;
			}
		}
		
		private decimal? m_labValue;
		public virtual decimal? LabValue
		{
			get
			{
				return this.m_labValue;
			}
			set
			{
				this.m_labValue = value;
			}
		}
		
		private decimal? m_relativeOffset;
		public virtual decimal? RelativeOffset
		{
			get
			{
				return this.m_relativeOffset;
			}
			set
			{
				this.m_relativeOffset = value;
			}
		}
		
		private decimal? m_compareLimitValue;
		public virtual decimal? CompareLimitValue
		{
			get
			{
				return this.m_compareLimitValue;
			}
			set
			{
				this.m_compareLimitValue = value;
			}
		}
		
		private decimal? m_offsetValue;
		public virtual decimal? OffsetValue
		{
			get
			{
				return this.m_offsetValue;
			}
			set
			{
				this.m_offsetValue = value;
			}
		}
		
		private string m_evaluate;
		public virtual string Evaluate
		{
			get
			{
				return this.m_evaluate;
			}
			set
			{
				this.m_evaluate = value;
			}
		}
		
		private DateTime? m_datetime;
		public virtual DateTime? Datetime
		{
			get
			{
				return this.m_datetime;
			}
			set
			{
				this.m_datetime = value;
			}
		}
		
		private string m_tester;
		public virtual string Tester
		{
			get
			{
				return this.m_tester;
			}
			set
			{
				this.m_tester = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_sampleNumber;
		public virtual string SampleNumber
		{
			get
			{
				return this.m_sampleNumber;
			}
			set
			{
				this.m_sampleNumber = value;
			}
		}
		
		private decimal? m_testValue;
		public virtual decimal? TestValue
		{
			get
			{
				return this.m_testValue;
			}
			set
			{
				this.m_testValue = value;
			}
		}
		
		private int m_id;
		public virtual int Id
		{
			get
			{
				return this.m_id;
			}
			set
			{
				this.m_id = value;
			}
		}
		
		private string m_compareItemName;
		public virtual string CompareItemName
		{
			get
			{
				return this.m_compareItemName;
			}
			set
			{
				this.m_compareItemName = value;
			}
		}
		
		private string m_pointName;
		public virtual string PointName
		{
			get
			{
				return this.m_pointName;
			}
			set
			{
				this.m_pointName = value;
			}
		}
		
		private string m_pointId;
		public virtual string PointId
		{
			get
			{
				return this.m_pointId;
			}
			set
			{
				this.m_pointId = value;
			}
		}
		
		private string m_taskCode;
		public virtual string TaskCode
		{
			get
			{
				return this.m_taskCode;
			}
			set
			{
				this.m_taskCode = value;
			}
		}
		
		private string m_testType;
		public virtual string TestType
		{
			get
			{
				return this.m_testType;
			}
			set
			{
				this.m_testType = value;
			}
		}
		
		private Guid? m_sampleGuid;
		public virtual Guid? SampleGuid
		{
			get
			{
				return this.m_sampleGuid;
			}
			set
			{
				this.m_sampleGuid = value;
			}
		}
		
		private string m_limit;
		public virtual string Limit
		{
			get
			{
				return this.m_limit;
			}
			set
			{
				this.m_limit = value;
			}
		}
		
		private decimal? m_absoluteOffset;
		public virtual decimal? AbsoluteOffset
		{
			get
			{
				return this.m_absoluteOffset;
			}
			set
			{
				this.m_absoluteOffset = value;
			}
		}
		
		private string m_remark;
		public virtual string Remark
		{
			get
			{
				return this.m_remark;
			}
			set
			{
				this.m_remark = value;
			}
		}
		
		private string m_itemNumber;
		public virtual string ItemNumber
		{
			get
			{
				return this.m_itemNumber;
			}
			set
			{
				this.m_itemNumber = value;
			}
		}
		
	}
}
#pragma warning restore 1591
