#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.MonitoringBusiness;

namespace SmartEP.DomainModel.MonitoringBusiness	
{
	public partial class ReportLogEntity : IMonitoringBusinessEntityProperty
	{
		private int m_id;
		public virtual int Id
		{
			get
			{
				return this.m_id;
			}
			set
			{
				this.m_id = value;
			}
		}
		
		private string m_pointIds;
		public virtual string PointIds
		{
			get
			{
				return this.m_pointIds;
			}
			set
			{
				this.m_pointIds = value;
			}
		}
		
		private string m_pointNames;
		public virtual string PointNames
		{
			get
			{
				return this.m_pointNames;
			}
			set
			{
				this.m_pointNames = value;
			}
		}
		
		private string m_factorCodes;
		public virtual string FactorCodes
		{
			get
			{
				return this.m_factorCodes;
			}
			set
			{
				this.m_factorCodes = value;
			}
		}
		
		private string m_factorsNames;
		public virtual string FactorsNames
		{
			get
			{
				return this.m_factorsNames;
			}
			set
			{
				this.m_factorsNames = value;
			}
		}
		
		private int? m_waterOrAirType;
		public virtual int? WaterOrAirType
		{
			get
			{
				return this.m_waterOrAirType;
			}
			set
			{
				this.m_waterOrAirType = value;
			}
		}
		
		private string m_pageTypeID;
		public virtual string PageTypeID
		{
			get
			{
				return this.m_pageTypeID;
			}
			set
			{
				this.m_pageTypeID = value;
			}
		}
		
		private DateTime? m_startDateTime;
		public virtual DateTime? StartDateTime
		{
			get
			{
				return this.m_startDateTime;
			}
			set
			{
				this.m_startDateTime = value;
			}
		}
		
		private DateTime? m_endDateTime;
		public virtual DateTime? EndDateTime
		{
			get
			{
				return this.m_endDateTime;
			}
			set
			{
				this.m_endDateTime = value;
			}
		}
		
		private string m_dateTimeRange;
		public virtual string DateTimeRange
		{
			get
			{
				return this.m_dateTimeRange;
			}
			set
			{
				this.m_dateTimeRange = value;
			}
		}
		
		private string m_reportName;
		public virtual string ReportName
		{
			get
			{
				return this.m_reportName;
			}
			set
			{
				this.m_reportName = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private string m_exportName;
		public virtual string ExportName
		{
			get
			{
				return this.m_exportName;
			}
			set
			{
				this.m_exportName = value;
			}
		}
		
	}
}
#pragma warning restore 1591
