#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.MonitoringBusiness;

namespace SmartEP.DomainModel.MonitoringBusiness	
{
	public partial class WeatherForcastEntity : IMonitoringBusinessEntityProperty
	{
		private string m_weatherForcastUid;
		public virtual string WeatherForcastUid
		{
			get
			{
				return this.m_weatherForcastUid;
			}
			set
			{
				this.m_weatherForcastUid = value;
			}
		}
		
		private DateTime? m_reportDateTime;
		public virtual DateTime? ReportDateTime
		{
			get
			{
				return this.m_reportDateTime;
			}
			set
			{
				this.m_reportDateTime = value;
			}
		}
		
		private string m_weather;
		public virtual string Weather
		{
			get
			{
				return this.m_weather;
			}
			set
			{
				this.m_weather = value;
			}
		}
		
		private string m_windSpeed;
		public virtual string WindSpeed
		{
			get
			{
				return this.m_windSpeed;
			}
			set
			{
				this.m_windSpeed = value;
			}
		}
		
		private string m_windDirection;
		public virtual string WindDirection
		{
			get
			{
				return this.m_windDirection;
			}
			set
			{
				this.m_windDirection = value;
			}
		}
		
		private string m_rainfall;
		public virtual string Rainfall
		{
			get
			{
				return this.m_rainfall;
			}
			set
			{
				this.m_rainfall = value;
			}
		}
		
		private string m_humidity;
		public virtual string Humidity
		{
			get
			{
				return this.m_humidity;
			}
			set
			{
				this.m_humidity = value;
			}
		}
		
		private string m_minTemp;
		public virtual string MinTemp
		{
			get
			{
				return this.m_minTemp;
			}
			set
			{
				this.m_minTemp = value;
			}
		}
		
		private string m_maxTemp;
		public virtual string MaxTemp
		{
			get
			{
				return this.m_maxTemp;
			}
			set
			{
				this.m_maxTemp = value;
			}
		}
		
		private string m_todayWeather;
		public virtual string TodayWeather
		{
			get
			{
				return this.m_todayWeather;
			}
			set
			{
				this.m_todayWeather = value;
			}
		}
		
		private string m_todayDiffusion;
		public virtual string TodayDiffusion
		{
			get
			{
				return this.m_todayDiffusion;
			}
			set
			{
				this.m_todayDiffusion = value;
			}
		}
		
		private string m_tomorrowWeather;
		public virtual string TomorrowWeather
		{
			get
			{
				return this.m_tomorrowWeather;
			}
			set
			{
				this.m_tomorrowWeather = value;
			}
		}
		
		private string m_tomorrowDiffusion;
		public virtual string TomorrowDiffusion
		{
			get
			{
				return this.m_tomorrowDiffusion;
			}
			set
			{
				this.m_tomorrowDiffusion = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
	}
}
#pragma warning restore 1591
