#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.MonitoringBusiness;

namespace SmartEP.DomainModel.MonitoringBusiness	
{
	public partial class AuditAirLogEntity : IMonitoringBusinessEntityProperty
	{
		private string m_auditLogUid;
		public virtual string AuditLogUid
		{
			get
			{
				return this.m_auditLogUid;
			}
			set
			{
				this.m_auditLogUid = value;
			}
		}
		
		private string m_auditStatusUid;
		public virtual string AuditStatusUid
		{
			get
			{
				return this.m_auditStatusUid;
			}
			set
			{
				this.m_auditStatusUid = value;
			}
		}
		
		private DateTime? m_tstamp;
		public virtual DateTime? Tstamp
		{
			get
			{
				return this.m_tstamp;
			}
			set
			{
				this.m_tstamp = value;
			}
		}
		
		private DateTime? m_auditTime;
		public virtual DateTime? AuditTime
		{
			get
			{
				return this.m_auditTime;
			}
			set
			{
				this.m_auditTime = value;
			}
		}
		
		private string m_auditType;
		public virtual string AuditType
		{
			get
			{
				return this.m_auditType;
			}
			set
			{
				this.m_auditType = value;
			}
		}
		
		private string m_pollutantCode;
		public virtual string PollutantCode
		{
			get
			{
				return this.m_pollutantCode;
			}
			set
			{
				this.m_pollutantCode = value;
			}
		}
		
		private string m_pollutantName;
		public virtual string PollutantName
		{
			get
			{
				return this.m_pollutantName;
			}
			set
			{
				this.m_pollutantName = value;
			}
		}
		
		private string m_sourcePollutantDataValue;
		public virtual string SourcePollutantDataValue
		{
			get
			{
				return this.m_sourcePollutantDataValue;
			}
			set
			{
				this.m_sourcePollutantDataValue = value;
			}
		}
		
		private string m_auditPollutantDataValue;
		public virtual string AuditPollutantDataValue
		{
			get
			{
				return this.m_auditPollutantDataValue;
			}
			set
			{
				this.m_auditPollutantDataValue = value;
			}
		}
		
		private string m_operationTypeEnum;
		public virtual string OperationTypeEnum
		{
			get
			{
				return this.m_operationTypeEnum;
			}
			set
			{
				this.m_operationTypeEnum = value;
			}
		}
		
		private string m_operationReason;
		public virtual string OperationReason
		{
			get
			{
				return this.m_operationReason;
			}
			set
			{
				this.m_operationReason = value;
			}
		}
		
		private string m_userIP;
		public virtual string UserIP
		{
			get
			{
				return this.m_userIP;
			}
			set
			{
				this.m_userIP = value;
			}
		}
		
		private string m_userUid;
		public virtual string UserUid
		{
			get
			{
				return this.m_userUid;
			}
			set
			{
				this.m_userUid = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private string m_instrumentName;
		public virtual string InstrumentName
		{
			get
			{
				return this.m_instrumentName;
			}
			set
			{
				this.m_instrumentName = value;
			}
		}
		
		private AuditStatusForDayEntity m_auditStatusForDayEntity;
		public virtual AuditStatusForDayEntity AuditStatusForDayEntity
		{
			get
			{
				return this.m_auditStatusForDayEntity;
			}
			set
			{
				this.m_auditStatusForDayEntity = value;
			}
		}
		
	}
}
#pragma warning restore 1591
