#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.MonitoringBusiness;

namespace SmartEP.DomainModel.MonitoringBusiness	
{
	public partial class AuditAirInfectantByMinuteEntity : IMonitoringBusinessEntityProperty
	{
		private string m_auditUid;
		public virtual string AuditUid
		{
			get
			{
				return this.m_auditUid;
			}
			set
			{
				this.m_auditUid = value;
			}
		}
		
		private string m_auditStatusUid;
		public virtual string AuditStatusUid
		{
			get
			{
				return this.m_auditStatusUid;
			}
			set
			{
				this.m_auditStatusUid = value;
			}
		}
		
		private string m_applicationUid;
		public virtual string ApplicationUid
		{
			get
			{
				return this.m_applicationUid;
			}
			set
			{
				this.m_applicationUid = value;
			}
		}
		
		private int m_pointId;
		public virtual int PointId
		{
			get
			{
				return this.m_pointId;
			}
			set
			{
				this.m_pointId = value;
			}
		}
		
		private DateTime? m_dataDateTime;
		public virtual DateTime? DataDateTime
		{
			get
			{
				return this.m_dataDateTime;
			}
			set
			{
				this.m_dataDateTime = value;
			}
		}
		
		private string m_dataFlag;
		public virtual string DataFlag
		{
			get
			{
				return this.m_dataFlag;
			}
			set
			{
				this.m_dataFlag = value;
			}
		}
		
		private string m_auditFlag;
		public virtual string AuditFlag
		{
			get
			{
				return this.m_auditFlag;
			}
			set
			{
				this.m_auditFlag = value;
			}
		}
		
		private string m_pollutantCode;
		public virtual string PollutantCode
		{
			get
			{
				return this.m_pollutantCode;
			}
			set
			{
				this.m_pollutantCode = value;
			}
		}
		
		private decimal? m_pollutantValue;
		public virtual decimal? PollutantValue
		{
			get
			{
				return this.m_pollutantValue;
			}
			set
			{
				this.m_pollutantValue = value;
			}
		}
		
		private string m_monitoringDataTypeCode;
		public virtual string MonitoringDataTypeCode
		{
			get
			{
				return this.m_monitoringDataTypeCode;
			}
			set
			{
				this.m_monitoringDataTypeCode = value;
			}
		}
		
		private string m_isAudit;
		public virtual string IsAudit
		{
			get
			{
				return this.m_isAudit;
			}
			set
			{
				this.m_isAudit = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private AuditStatusForDayEntity m_auditStatusForDayEntity;
		public virtual AuditStatusForDayEntity AuditStatusForDayEntity
		{
			get
			{
				return this.m_auditStatusForDayEntity;
			}
			set
			{
				this.m_auditStatusForDayEntity = value;
			}
		}
		
	}
}
#pragma warning restore 1591
