#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.MonitoringBusiness;

namespace SmartEP.DomainModel.MonitoringBusiness	
{
	public partial class WaterMonthRunReportSettingEntity : IMonitoringBusinessEntityProperty
	{
		private int m_reportID;
		public virtual int ReportID
		{
			get
			{
				return this.m_reportID;
			}
			set
			{
				this.m_reportID = value;
			}
		}
		
		private DateTime? m_reportTime;
		public virtual DateTime? ReportTime
		{
			get
			{
				return this.m_reportTime;
			}
			set
			{
				this.m_reportTime = value;
			}
		}
		
		private string m_pointIDs;
		public virtual string PointIDs
		{
			get
			{
				return this.m_pointIDs;
			}
			set
			{
				this.m_pointIDs = value;
			}
		}
		
		private string m_factorCodes;
		public virtual string FactorCodes
		{
			get
			{
				return this.m_factorCodes;
			}
			set
			{
				this.m_factorCodes = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_result;
		public virtual string Result
		{
			get
			{
				return this.m_result;
			}
			set
			{
				this.m_result = value;
			}
		}
		
		private string m_memo;
		public virtual string Memo
		{
			get
			{
				return this.m_memo;
			}
			set
			{
				this.m_memo = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
	}
}
#pragma warning restore 1591
