#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.BaseData;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class AcquisitionInstrumentEntity : IMPInfoEntityProperty
	{
		private string m_acquisitionUid;
		public virtual string AcquisitionUid
		{
			get
			{
				return this.m_acquisitionUid;
			}
			set
			{
				this.m_acquisitionUid = value;
			}
		}
		
		private string m_monitoringPointUid;
		public virtual string MonitoringPointUid
		{
			get
			{
				return this.m_monitoringPointUid;
			}
			set
			{
				this.m_monitoringPointUid = value;
			}
		}
		
		private string m_acquisitionName;
		public virtual string AcquisitionName
		{
			get
			{
				return this.m_acquisitionName;
			}
			set
			{
				this.m_acquisitionName = value;
			}
		}
		
		private string m_dataTypeCode;
		public virtual string DataTypeCode
		{
			get
			{
				return this.m_dataTypeCode;
			}
			set
			{
				this.m_dataTypeCode = value;
			}
		}
		
		private string m_acquisitionFrequency;
		public virtual string AcquisitionFrequency
		{
			get
			{
				return this.m_acquisitionFrequency;
			}
			set
			{
				this.m_acquisitionFrequency = value;
			}
		}
		
		private string m_mN;
		public virtual string MN
		{
			get
			{
				return this.m_mN;
			}
			set
			{
				this.m_mN = value;
			}
		}
		
		private string m_communicationUid;
		public virtual string CommunicationUid
		{
			get
			{
				return this.m_communicationUid;
			}
			set
			{
				this.m_communicationUid = value;
			}
		}
		
		private string m_communicationPort;
		public virtual string CommunicationPort
		{
			get
			{
				return this.m_communicationPort;
			}
			set
			{
				this.m_communicationPort = value;
			}
		}
		
		private string m_manufactureUid;
		public virtual string ManufactureUid
		{
			get
			{
				return this.m_manufactureUid;
			}
			set
			{
				this.m_manufactureUid = value;
			}
		}
		
		private string m_iP;
		public virtual string IP
		{
			get
			{
				return this.m_iP;
			}
			set
			{
				this.m_iP = value;
			}
		}
		
		private string m_ipUser;
		public virtual string IpUser
		{
			get
			{
				return this.m_ipUser;
			}
			set
			{
				this.m_ipUser = value;
			}
		}
		
		private string m_ipPwd;
		public virtual string IpPwd
		{
			get
			{
				return this.m_ipPwd;
			}
			set
			{
				this.m_ipPwd = value;
			}
		}
		
		private bool? m_aCKOrNot;
		public virtual bool? ACKOrNot
		{
			get
			{
				return this.m_aCKOrNot;
			}
			set
			{
				this.m_aCKOrNot = value;
			}
		}
		
		private bool? m_cRCOrNot;
		public virtual bool? CRCOrNot
		{
			get
			{
				return this.m_cRCOrNot;
			}
			set
			{
				this.m_cRCOrNot = value;
			}
		}
		
		private bool? m_encryptionOrNot;
		public virtual bool? EncryptionOrNot
		{
			get
			{
				return this.m_encryptionOrNot;
			}
			set
			{
				this.m_encryptionOrNot = value;
			}
		}
		
		private int? m_retransmissionNum;
		public virtual int? RetransmissionNum
		{
			get
			{
				return this.m_retransmissionNum;
			}
			set
			{
				this.m_retransmissionNum = value;
			}
		}
		
		private int? m_excessiveCount;
		public virtual int? ExcessiveCount
		{
			get
			{
				return this.m_excessiveCount;
			}
			set
			{
				this.m_excessiveCount = value;
			}
		}
		
		private string m_encryptionKey;
		public virtual string EncryptionKey
		{
			get
			{
				return this.m_encryptionKey;
			}
			set
			{
				this.m_encryptionKey = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
	}
}
#pragma warning restore 1591
