#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.BaseData;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class CommunicationInfoEntity : IMPInfoEntityProperty
	{
		private string m_communicationUid;
		public virtual string CommunicationUid
		{
			get
			{
				return this.m_communicationUid;
			}
			set
			{
				this.m_communicationUid = value;
			}
		}
		
		private byte[] m_acquisitionUid;
		public virtual byte[] AcquisitionUid
		{
			get
			{
				return this.m_acquisitionUid;
			}
			set
			{
				this.m_acquisitionUid = value;
			}
		}
		
		private string m_serverceMunufactureUid;
		public virtual string ServerceMunufactureUid
		{
			get
			{
				return this.m_serverceMunufactureUid;
			}
			set
			{
				this.m_serverceMunufactureUid = value;
			}
		}
		
		private string m_communicationUser;
		public virtual string CommunicationUser
		{
			get
			{
				return this.m_communicationUser;
			}
			set
			{
				this.m_communicationUser = value;
			}
		}
		
		private string m_communicationPwd;
		public virtual string CommunicationPwd
		{
			get
			{
				return this.m_communicationPwd;
			}
			set
			{
				this.m_communicationPwd = value;
			}
		}
		
		private string m_dGITypeUid;
		public virtual string DGITypeUid
		{
			get
			{
				return this.m_dGITypeUid;
			}
			set
			{
				this.m_dGITypeUid = value;
			}
		}
		
		private decimal? m_accountBalance;
		public virtual decimal? AccountBalance
		{
			get
			{
				return this.m_accountBalance;
			}
			set
			{
				this.m_accountBalance = value;
			}
		}
		
		private DateTime? m_openingTime;
		public virtual DateTime? OpeningTime
		{
			get
			{
				return this.m_openingTime;
			}
			set
			{
				this.m_openingTime = value;
			}
		}
		
		private DateTime? m_deadline;
		public virtual DateTime? Deadline
		{
			get
			{
				return this.m_deadline;
			}
			set
			{
				this.m_deadline = value;
			}
		}
		
		private decimal? m_thisMonthUploadFlow;
		public virtual decimal? ThisMonthUploadFlow
		{
			get
			{
				return this.m_thisMonthUploadFlow;
			}
			set
			{
				this.m_thisMonthUploadFlow = value;
			}
		}
		
		private decimal? m_thisMonthDownloadFlow;
		public virtual decimal? ThisMonthDownloadFlow
		{
			get
			{
				return this.m_thisMonthDownloadFlow;
			}
			set
			{
				this.m_thisMonthDownloadFlow = value;
			}
		}
		
		private decimal? m_totalFlow;
		public virtual decimal? TotalFlow
		{
			get
			{
				return this.m_totalFlow;
			}
			set
			{
				this.m_totalFlow = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
	}
}
#pragma warning restore 1591
