#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Model;

namespace Model	
{
	public partial class MonitorBusinessModel : OpenAccessContext, IMonitorBusinessModelUnitOfWork
	{
		private static string connectionStringName = @"AMS_MonitorBusinessConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("MonitorBusinessModel.rlinq");
		
		public MonitorBusinessModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public MonitorBusinessModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public MonitorBusinessModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public MonitorBusinessModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public MonitorBusinessModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<InstrumentDataOnline> InstrumentDataOnlines 
		{
			get
			{
				return this.GetAll<InstrumentDataOnline>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of MonitorBusinessModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of MonitorBusinessModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IMonitorBusinessModelUnitOfWork : IUnitOfWork
	{
		IQueryable<InstrumentDataOnline> InstrumentDataOnlines
		{
			get;
		}
	}
}
#pragma warning restore 1591
