#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.BaseData;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class NotifyTypeEntity : IAlarmNotifyEntityProperty
	{
		private string m_notifyTypeUid;
		public virtual string NotifyTypeUid
		{
			get
			{
				return this.m_notifyTypeUid;
			}
			set
			{
				this.m_notifyTypeUid = value;
			}
		}
		
		private string m_notifyTypeName;
		public virtual string NotifyTypeName
		{
			get
			{
				return this.m_notifyTypeName;
			}
			set
			{
				this.m_notifyTypeName = value;
			}
		}
		
		private string m_connectionNumber;
		public virtual string ConnectionNumber
		{
			get
			{
				return this.m_connectionNumber;
			}
			set
			{
				this.m_connectionNumber = value;
			}
		}
		
		private string m_connectionPort;
		public virtual string ConnectionPort
		{
			get
			{
				return this.m_connectionPort;
			}
			set
			{
				this.m_connectionPort = value;
			}
		}
		
		private string m_loginID;
		public virtual string LoginID
		{
			get
			{
				return this.m_loginID;
			}
			set
			{
				this.m_loginID = value;
			}
		}
		
		private string m_password;
		public virtual string Password
		{
			get
			{
				return this.m_password;
			}
			set
			{
				this.m_password = value;
			}
		}
		
		private string m_connectionString;
		public virtual string ConnectionString
		{
			get
			{
				return this.m_connectionString;
			}
			set
			{
				this.m_connectionString = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private IList<NotifyGradeEntity> m_notifyGradeEntities = new List<NotifyGradeEntity>();
		public virtual IList<NotifyGradeEntity> NotifyGradeEntities
		{
			get
			{
				return this.m_notifyGradeEntities;
			}
		}
		
	}
}
#pragma warning restore 1591
