#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Model;

namespace Model	
{
	public partial class AirAutoMonitorModel : OpenAccessContext, IAirAutoMonitorUnitOfWork
	{
		private static string connectionStringName = @"AMS_AirAutoMonitorConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("AirAutoMonitorModel.rlinq");
		
		public AirAutoMonitorModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public AirAutoMonitorModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public AirAutoMonitorModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public AirAutoMonitorModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public AirAutoMonitorModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<TB_InfectantBy60Buffer> TB_InfectantBy60Buffers 
		{
			get
			{
				return this.GetAll<TB_InfectantBy60Buffer>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of AirAutoMonitor.
		/// </summary>
		/// <param name="config">The BackendConfiguration of AirAutoMonitor.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IAirAutoMonitorUnitOfWork : IUnitOfWork
	{
		IQueryable<TB_InfectantBy60Buffer> TB_InfectantBy60Buffers
		{
			get;
		}
	}
}
#pragma warning restore 1591
