#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Model;

namespace Model	
{
	public partial class BaseDataModel : OpenAccessContext, IBaseDataModelUnitOfWork
	{
		private static string connectionStringName = @"AMS_BaseDataConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("BaseDataModel.rlinq");
		
		public BaseDataModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public BaseDataModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public BaseDataModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public BaseDataModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public BaseDataModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<SYS_Point_Mapping> SYS_Point_Mappings 
		{
			get
			{
				return this.GetAll<SYS_Point_Mapping>();
			}
		}
		
		public IQueryable<SYS_Factors_Mapping> SYS_Factors_Mappings 
		{
			get
			{
				return this.GetAll<SYS_Factors_Mapping>();
			}
		}
		
		public IQueryable<SYS_PointsFactors_Mapping> SYS_PointsFactors_Mappings 
		{
			get
			{
				return this.GetAll<SYS_PointsFactors_Mapping>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of BaseDataModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of BaseDataModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IBaseDataModelUnitOfWork : IUnitOfWork
	{
		IQueryable<SYS_Point_Mapping> SYS_Point_Mappings
		{
			get;
		}
		IQueryable<SYS_Factors_Mapping> SYS_Factors_Mappings
		{
			get;
		}
		IQueryable<SYS_PointsFactors_Mapping> SYS_PointsFactors_Mappings
		{
			get;
		}
	}
}
#pragma warning restore 1591
