#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Model	
{
	public partial class SYS_Factors_Mapping
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _rowGuid;
		public virtual string RowGuid
		{
			get
			{
				return this._rowGuid;
			}
			set
			{
				this._rowGuid = value;
			}
		}
		
		private string _wSCode;
		public virtual string WSCode
		{
			get
			{
				return this._wSCode;
			}
			set
			{
				this._wSCode = value;
			}
		}
		
		private string _localCode;
		public virtual string LocalCode
		{
			get
			{
				return this._localCode;
			}
			set
			{
				this._localCode = value;
			}
		}
		
		private int? _multiple;
		public virtual int? Multiple
		{
			get
			{
				return this._multiple;
			}
			set
			{
				this._multiple = value;
			}
		}
		
		private string _oRDERBYNUM;
		public virtual string ORDERBYNUM
		{
			get
			{
				return this._oRDERBYNUM;
			}
			set
			{
				this._oRDERBYNUM = value;
			}
		}
		
		private string _dESCRIPTION;
		public virtual string DESCRIPTION
		{
			get
			{
				return this._dESCRIPTION;
			}
			set
			{
				this._dESCRIPTION = value;
			}
		}
		
		private string _cREATUSER;
		public virtual string CREATUSER
		{
			get
			{
				return this._cREATUSER;
			}
			set
			{
				this._cREATUSER = value;
			}
		}
		
		private DateTime? _cREATDATETIME;
		public virtual DateTime? CREATDATETIME
		{
			get
			{
				return this._cREATDATETIME;
			}
			set
			{
				this._cREATDATETIME = value;
			}
		}
		
		private string _uPDATEUSER;
		public virtual string UPDATEUSER
		{
			get
			{
				return this._uPDATEUSER;
			}
			set
			{
				this._uPDATEUSER = value;
			}
		}
		
		private DateTime? _uPDATEDATETIME;
		public virtual DateTime? UPDATEDATETIME
		{
			get
			{
				return this._uPDATEDATETIME;
			}
			set
			{
				this._uPDATEDATETIME = value;
			}
		}
		
	}
}
#pragma warning restore 1591
