//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadFilter {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadFilter.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add Expression 的本地化字符串。
        /// </summary>
        internal static string AddExpressionToolTip {
            get {
                return ResourceManager.GetString("AddExpressionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Group 的本地化字符串。
        /// </summary>
        internal static string AddGroupToolTip {
            get {
                return ResourceManager.GetString("AddGroupToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        internal static string ApplyButtonText {
            get {
                return ResourceManager.GetString("ApplyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        internal static string BetweenDelimeterText {
            get {
                return ResourceManager.GetString("BetweenDelimeterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Between 的本地化字符串。
        /// </summary>
        internal static string FilterFunctionBetween {
            get {
                return ResourceManager.GetString("FilterFunctionBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contains 的本地化字符串。
        /// </summary>
        internal static string FilterFunctionContains {
            get {
                return ResourceManager.GetString("FilterFunctionContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DoesNotContain 的本地化字符串。
        /// </summary>
        internal static string FilterFunctionDoesNotContain {
            get {
                return ResourceManager.GetString("FilterFunctionDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndsWith 的本地化字符串。
        /// </summary>
        internal static string FilterFunctionEndsWith {
            get {
                return ResourceManager.GetString("FilterFunctionEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EqualTo 的本地化字符串。
        /// </summary>
        internal static string FilterFunctionEqualTo {
            get {
                return ResourceManager.GetString("FilterFunctionEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GreaterThan 的本地化字符串。
        /// </summary>
        internal static string FilterFunctionGreaterThan {
            get {
                return ResourceManager.GetString("FilterFunctionGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GreaterThanOrEqualTo 的本地化字符串。
        /// </summary>
        internal static string FilterFunctionGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterFunctionGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsEmpty 的本地化字符串。
        /// </summary>
        internal static string FilterFunctionIsEmpty {
            get {
                return ResourceManager.GetString("FilterFunctionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsNull 的本地化字符串。
        /// </summary>
        internal static string FilterFunctionIsNull {
            get {
                return ResourceManager.GetString("FilterFunctionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LessThan 的本地化字符串。
        /// </summary>
        internal static string FilterFunctionLessThan {
            get {
                return ResourceManager.GetString("FilterFunctionLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LessThanOrEqualTo 的本地化字符串。
        /// </summary>
        internal static string FilterFunctionLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterFunctionLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotBetween 的本地化字符串。
        /// </summary>
        internal static string FilterFunctionNotBetween {
            get {
                return ResourceManager.GetString("FilterFunctionNotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotEqualTo 的本地化字符串。
        /// </summary>
        internal static string FilterFunctionNotEqualTo {
            get {
                return ResourceManager.GetString("FilterFunctionNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotIsEmpty 的本地化字符串。
        /// </summary>
        internal static string FilterFunctionNotIsEmpty {
            get {
                return ResourceManager.GetString("FilterFunctionNotIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotIsNull 的本地化字符串。
        /// </summary>
        internal static string FilterFunctionNotIsNull {
            get {
                return ResourceManager.GetString("FilterFunctionNotIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartsWith 的本地化字符串。
        /// </summary>
        internal static string FilterFunctionStartsWith {
            get {
                return ResourceManager.GetString("FilterFunctionStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        internal static string GroupOperationAnd {
            get {
                return ResourceManager.GetString("GroupOperationAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not And 的本地化字符串。
        /// </summary>
        internal static string GroupOperationNotAnd {
            get {
                return ResourceManager.GetString("GroupOperationNotAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Or 的本地化字符串。
        /// </summary>
        internal static string GroupOperationNotOr {
            get {
                return ResourceManager.GetString("GroupOperationNotOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Or 的本地化字符串。
        /// </summary>
        internal static string GroupOperationOr {
            get {
                return ResourceManager.GetString("GroupOperationOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Item 的本地化字符串。
        /// </summary>
        internal static string RemoveToolTip {
            get {
                return ResourceManager.GetString("RemoveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please do not remove this key. 的本地化字符串。
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
    }
}
