//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadScheduler {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadScheduler.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 All day 的本地化字符串。
        /// </summary>
        internal static string AdvancedAllDayEvent {
            get {
                return ResourceManager.GetString("AdvancedAllDayEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string AdvancedCalendarCancel {
            get {
                return ResourceManager.GetString("AdvancedCalendarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string AdvancedCalendarOK {
            get {
                return ResourceManager.GetString("AdvancedCalendarOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        internal static string AdvancedCalendarToday {
            get {
                return ResourceManager.GetString("AdvancedCalendarToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string AdvancedClose {
            get {
                return ResourceManager.GetString("AdvancedClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Daily 的本地化字符串。
        /// </summary>
        internal static string AdvancedDaily {
            get {
                return ResourceManager.GetString("AdvancedDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Day 的本地化字符串。
        /// </summary>
        internal static string AdvancedDay {
            get {
                return ResourceManager.GetString("AdvancedDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 day(s) 的本地化字符串。
        /// </summary>
        internal static string AdvancedDays {
            get {
                return ResourceManager.GetString("AdvancedDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string AdvancedDescription {
            get {
                return ResourceManager.GetString("AdvancedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        internal static string AdvancedDone {
            get {
                return ResourceManager.GetString("AdvancedDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Appointment 的本地化字符串。
        /// </summary>
        internal static string AdvancedEditAppointment {
            get {
                return ResourceManager.GetString("AdvancedEditAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End after 的本地化字符串。
        /// </summary>
        internal static string AdvancedEndAfter {
            get {
                return ResourceManager.GetString("AdvancedEndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End by 的本地化字符串。
        /// </summary>
        internal static string AdvancedEndByThisDate {
            get {
                return ResourceManager.GetString("AdvancedEndByThisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End date is required 的本地化字符串。
        /// </summary>
        internal static string AdvancedEndDateRequired {
            get {
                return ResourceManager.GetString("AdvancedEndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End time is required 的本地化字符串。
        /// </summary>
        internal static string AdvancedEndTimeRequired {
            get {
                return ResourceManager.GetString("AdvancedEndTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every 的本地化字符串。
        /// </summary>
        internal static string AdvancedEvery {
            get {
                return ResourceManager.GetString("AdvancedEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every weekday 的本地化字符串。
        /// </summary>
        internal static string AdvancedEveryWeekday {
            get {
                return ResourceManager.GetString("AdvancedEveryWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 first 的本地化字符串。
        /// </summary>
        internal static string AdvancedFirst {
            get {
                return ResourceManager.GetString("AdvancedFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fourth 的本地化字符串。
        /// </summary>
        internal static string AdvancedFourth {
            get {
                return ResourceManager.GetString("AdvancedFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start time 的本地化字符串。
        /// </summary>
        internal static string AdvancedFrom {
            get {
                return ResourceManager.GetString("AdvancedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hourly 的本地化字符串。
        /// </summary>
        internal static string AdvancedHourly {
            get {
                return ResourceManager.GetString("AdvancedHourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hour(s) 的本地化字符串。
        /// </summary>
        internal static string AdvancedHours {
            get {
                return ResourceManager.GetString("AdvancedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid number 的本地化字符串。
        /// </summary>
        internal static string AdvancedInvalidNumber {
            get {
                return ResourceManager.GetString("AdvancedInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 last 的本地化字符串。
        /// </summary>
        internal static string AdvancedLast {
            get {
                return ResourceManager.GetString("AdvancedLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 day 的本地化字符串。
        /// </summary>
        internal static string AdvancedMaskDay {
            get {
                return ResourceManager.GetString("AdvancedMaskDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 weekday 的本地化字符串。
        /// </summary>
        internal static string AdvancedMaskWeekday {
            get {
                return ResourceManager.GetString("AdvancedMaskWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 weekend day 的本地化字符串。
        /// </summary>
        internal static string AdvancedMaskWeekendDay {
            get {
                return ResourceManager.GetString("AdvancedMaskWeekendDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monthly 的本地化字符串。
        /// </summary>
        internal static string AdvancedMonthly {
            get {
                return ResourceManager.GetString("AdvancedMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 month(s) 的本地化字符串。
        /// </summary>
        internal static string AdvancedMonths {
            get {
                return ResourceManager.GetString("AdvancedMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More details 的本地化字符串。
        /// </summary>
        internal static string AdvancedMoreDetails {
            get {
                return ResourceManager.GetString("AdvancedMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Appointment 的本地化字符串。
        /// </summary>
        internal static string AdvancedNewAppointment {
            get {
                return ResourceManager.GetString("AdvancedNewAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No end date 的本地化字符串。
        /// </summary>
        internal static string AdvancedNoEndDate {
            get {
                return ResourceManager.GetString("AdvancedNoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 occurrences 的本地化字符串。
        /// </summary>
        internal static string AdvancedOccurrences {
            get {
                return ResourceManager.GetString("AdvancedOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of 的本地化字符串。
        /// </summary>
        internal static string AdvancedOf {
            get {
                return ResourceManager.GetString("AdvancedOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of every 的本地化字符串。
        /// </summary>
        internal static string AdvancedOfEvery {
            get {
                return ResourceManager.GetString("AdvancedOfEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range of recurrence: 的本地化字符串。
        /// </summary>
        internal static string AdvancedRange {
            get {
                return ResourceManager.GetString("AdvancedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recur every 的本地化字符串。
        /// </summary>
        internal static string AdvancedRecurEvery {
            get {
                return ResourceManager.GetString("AdvancedRecurEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recurrence 的本地化字符串。
        /// </summary>
        internal static string AdvancedRecurrence {
            get {
                return ResourceManager.GetString("AdvancedRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recurring task 的本地化字符串。
        /// </summary>
        internal static string AdvancedRecurringAppointment {
            get {
                return ResourceManager.GetString("AdvancedRecurringAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 reset exceptions 的本地化字符串。
        /// </summary>
        internal static string AdvancedReset {
            get {
                return ResourceManager.GetString("AdvancedReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 second 的本地化字符串。
        /// </summary>
        internal static string AdvancedSecond {
            get {
                return ResourceManager.GetString("AdvancedSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start date is required 的本地化字符串。
        /// </summary>
        internal static string AdvancedStartDateRequired {
            get {
                return ResourceManager.GetString("AdvancedStartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start time must be before end time 的本地化字符串。
        /// </summary>
        internal static string AdvancedStartTimeBeforeEndTime {
            get {
                return ResourceManager.GetString("AdvancedStartTimeBeforeEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start time is required 的本地化字符串。
        /// </summary>
        internal static string AdvancedStartTimeRequired {
            get {
                return ResourceManager.GetString("AdvancedStartTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subject 的本地化字符串。
        /// </summary>
        internal static string AdvancedSubject {
            get {
                return ResourceManager.GetString("AdvancedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please provide appointment subject 的本地化字符串。
        /// </summary>
        internal static string AdvancedSubjectRequired {
            get {
                return ResourceManager.GetString("AdvancedSubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The 的本地化字符串。
        /// </summary>
        internal static string AdvancedThe {
            get {
                return ResourceManager.GetString("AdvancedThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 third 的本地化字符串。
        /// </summary>
        internal static string AdvancedThird {
            get {
                return ResourceManager.GetString("AdvancedThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time zone 的本地化字符串。
        /// </summary>
        internal static string AdvancedTimeZone {
            get {
                return ResourceManager.GetString("AdvancedTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End time 的本地化字符串。
        /// </summary>
        internal static string AdvancedTo {
            get {
                return ResourceManager.GetString("AdvancedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weekly 的本地化字符串。
        /// </summary>
        internal static string AdvancedWeekly {
            get {
                return ResourceManager.GetString("AdvancedWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 week(s) on 的本地化字符串。
        /// </summary>
        internal static string AdvancedWeeks {
            get {
                return ResourceManager.GetString("AdvancedWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Working... 的本地化字符串。
        /// </summary>
        internal static string AdvancedWorking {
            get {
                return ResourceManager.GetString("AdvancedWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yearly 的本地化字符串。
        /// </summary>
        internal static string AdvancedYearly {
            get {
                return ResourceManager.GetString("AdvancedYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 all day 的本地化字符串。
        /// </summary>
        internal static string AllDay {
            get {
                return ResourceManager.GetString("AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string ConfirmCancel {
            get {
                return ResourceManager.GetString("ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this appointment? 的本地化字符串。
        /// </summary>
        internal static string ConfirmDeleteText {
            get {
                return ResourceManager.GetString("ConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm delete 的本地化字符串。
        /// </summary>
        internal static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string ConfirmOK {
            get {
                return ResourceManager.GetString("ConfirmOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete only this occurrence. 的本地化字符串。
        /// </summary>
        internal static string ConfirmRecurrenceDeleteOccurrence {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceDeleteOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete the series. 的本地化字符串。
        /// </summary>
        internal static string ConfirmRecurrenceDeleteSeries {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceDeleteSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleting a recurring appointment 的本地化字符串。
        /// </summary>
        internal static string ConfirmRecurrenceDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit only this occurrence. 的本地化字符串。
        /// </summary>
        internal static string ConfirmRecurrenceEditOccurrence {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceEditOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit the series. 的本地化字符串。
        /// </summary>
        internal static string ConfirmRecurrenceEditSeries {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceEditSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editing a recurring appointment 的本地化字符串。
        /// </summary>
        internal static string ConfirmRecurrenceEditTitle {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move only this occurrence. 的本地化字符串。
        /// </summary>
        internal static string ConfirmRecurrenceMoveOccurrence {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceMoveOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move the series. 的本地化字符串。
        /// </summary>
        internal static string ConfirmRecurrenceMoveSeries {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceMoveSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moving a recurring appointment 的本地化字符串。
        /// </summary>
        internal static string ConfirmRecurrenceMoveTitle {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceMoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resize only this occurrence. 的本地化字符串。
        /// </summary>
        internal static string ConfirmRecurrenceResizeOccurrence {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceResizeOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resize the series. 的本地化字符串。
        /// </summary>
        internal static string ConfirmRecurrenceResizeSeries {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceResizeSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resizing a recurring appointment 的本地化字符串。
        /// </summary>
        internal static string ConfirmRecurrenceResizeTitle {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceResizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to delete all existing recurrence exceptions? 的本地化字符串。
        /// </summary>
        internal static string ConfirmResetExceptionsText {
            get {
                return ResourceManager.GetString("ConfirmResetExceptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm reset exceptions 的本地化字符串。
        /// </summary>
        internal static string ConfirmResetExceptionsTitle {
            get {
                return ResourceManager.GetString("ConfirmResetExceptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Appointment 的本地化字符串。
        /// </summary>
        internal static string ContextMenuAddAppointment {
            get {
                return ResourceManager.GetString("ContextMenuAddAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Recurring Appointment 的本地化字符串。
        /// </summary>
        internal static string ContextMenuAddRecurringAppointment {
            get {
                return ResourceManager.GetString("ContextMenuAddRecurringAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string ContextMenuEdit {
            get {
                return ResourceManager.GetString("ContextMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to today 的本地化字符串。
        /// </summary>
        internal static string ContextMenuGoToToday {
            get {
                return ResourceManager.GetString("ContextMenuGoToToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Day 的本地化字符串。
        /// </summary>
        internal static string HeaderDay {
            get {
                return ResourceManager.GetString("HeaderDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Month 的本地化字符串。
        /// </summary>
        internal static string HeaderMonth {
            get {
                return ResourceManager.GetString("HeaderMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multi-day 的本地化字符串。
        /// </summary>
        internal static string HeaderMultiDay {
            get {
                return ResourceManager.GetString("HeaderMultiDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 next day 的本地化字符串。
        /// </summary>
        internal static string HeaderNextDay {
            get {
                return ResourceManager.GetString("HeaderNextDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 previous day 的本地化字符串。
        /// </summary>
        internal static string HeaderPrevDay {
            get {
                return ResourceManager.GetString("HeaderPrevDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeline 的本地化字符串。
        /// </summary>
        internal static string HeaderTimeline {
            get {
                return ResourceManager.GetString("HeaderTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 today 的本地化字符串。
        /// </summary>
        internal static string HeaderToday {
            get {
                return ResourceManager.GetString("HeaderToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Week 的本地化字符串。
        /// </summary>
        internal static string HeaderWeek {
            get {
                return ResourceManager.GetString("HeaderWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reminder 的本地化字符串。
        /// </summary>
        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 before start 的本地化字符串。
        /// </summary>
        internal static string ReminderBeforeStart {
            get {
                return ResourceManager.GetString("ReminderBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 day 的本地化字符串。
        /// </summary>
        internal static string ReminderDay {
            get {
                return ResourceManager.GetString("ReminderDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 days 的本地化字符串。
        /// </summary>
        internal static string ReminderDays {
            get {
                return ResourceManager.GetString("ReminderDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dismiss 的本地化字符串。
        /// </summary>
        internal static string ReminderDismiss {
            get {
                return ResourceManager.GetString("ReminderDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dismiss All 的本地化字符串。
        /// </summary>
        internal static string ReminderDismissAll {
            get {
                return ResourceManager.GetString("ReminderDismissAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 due in 的本地化字符串。
        /// </summary>
        internal static string ReminderDueIn {
            get {
                return ResourceManager.GetString("ReminderDueIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hour 的本地化字符串。
        /// </summary>
        internal static string ReminderHour {
            get {
                return ResourceManager.GetString("ReminderHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hours 的本地化字符串。
        /// </summary>
        internal static string ReminderHours {
            get {
                return ResourceManager.GetString("ReminderHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minute 的本地化字符串。
        /// </summary>
        internal static string ReminderMinute {
            get {
                return ResourceManager.GetString("ReminderMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minutes 的本地化字符串。
        /// </summary>
        internal static string ReminderMinutes {
            get {
                return ResourceManager.GetString("ReminderMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string ReminderNone {
            get {
                return ResourceManager.GetString("ReminderNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Item 的本地化字符串。
        /// </summary>
        internal static string ReminderOpenItem {
            get {
                return ResourceManager.GetString("ReminderOpenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 overdue 的本地化字符串。
        /// </summary>
        internal static string ReminderOverdue {
            get {
                return ResourceManager.GetString("ReminderOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reminders 的本地化字符串。
        /// </summary>
        internal static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snooze 的本地化字符串。
        /// </summary>
        internal static string ReminderSnooze {
            get {
                return ResourceManager.GetString("ReminderSnooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Snooze to be reminded again in: 的本地化字符串。
        /// </summary>
        internal static string ReminderSnoozeHint {
            get {
                return ResourceManager.GetString("ReminderSnoozeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 week 的本地化字符串。
        /// </summary>
        internal static string ReminderWeek {
            get {
                return ResourceManager.GetString("ReminderWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 weeks 的本地化字符串。
        /// </summary>
        internal static string ReminderWeeks {
            get {
                return ResourceManager.GetString("ReminderWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please do not remove this key. 的本地化字符串。
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 24 hours... 的本地化字符串。
        /// </summary>
        internal static string Show24Hours {
            get {
                return ResourceManager.GetString("Show24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        internal static string ShowAdvancedForm {
            get {
                return ResourceManager.GetString("ShowAdvancedForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show business hours... 的本地化字符串。
        /// </summary>
        internal static string ShowBusinessHours {
            get {
                return ResourceManager.GetString("ShowBusinessHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 more... 的本地化字符串。
        /// </summary>
        internal static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
    }
}
