#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Model	
{
	public partial class TB_InstrumentChannel
	{
		private string _instrumentChannelsUid;
		public virtual string InstrumentChannelsUid
		{
			get
			{
				return this._instrumentChannelsUid;
			}
			set
			{
				this._instrumentChannelsUid = value;
			}
		}
		
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _rowGuid;
		public virtual string RowGuid
		{
			get
			{
				return this._rowGuid;
			}
			set
			{
				this._rowGuid = value;
			}
		}
		
		private string _instrumentUid;
		public virtual string InstrumentUid
		{
			get
			{
				return this._instrumentUid;
			}
			set
			{
				this._instrumentUid = value;
			}
		}
		
		private string _pollutantUid;
		public virtual string PollutantUid
		{
			get
			{
				return this._pollutantUid;
			}
			set
			{
				this._pollutantUid = value;
			}
		}
		
		private string _pollutantCode;
		public virtual string PollutantCode
		{
			get
			{
				return this._pollutantCode;
			}
			set
			{
				this._pollutantCode = value;
			}
		}
		
		private string _pollutantName;
		public virtual string PollutantName
		{
			get
			{
				return this._pollutantName;
			}
			set
			{
				this._pollutantName = value;
			}
		}
		
		private string _useUid;
		public virtual string UseUid
		{
			get
			{
				return this._useUid;
			}
			set
			{
				this._useUid = value;
			}
		}
		
		private int? _orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this._orderByNum;
			}
			set
			{
				this._orderByNum = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private string _creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this._creatUser;
			}
			set
			{
				this._creatUser = value;
			}
		}
		
		private DateTime? _creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this._creatDateTime;
			}
			set
			{
				this._creatDateTime = value;
			}
		}
		
		private string _updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this._updateUser;
			}
			set
			{
				this._updateUser = value;
			}
		}
		
		private DateTime? _updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this._updateDateTime;
			}
			set
			{
				this._updateDateTime = value;
			}
		}
		
		private DateTime? _addDate;
		public virtual DateTime? AddDate
		{
			get
			{
				return this._addDate;
			}
			set
			{
				this._addDate = value;
			}
		}
		
		private string _addUserGuid;
		public virtual string AddUserGuid
		{
			get
			{
				return this._addUserGuid;
			}
			set
			{
				this._addUserGuid = value;
			}
		}
		
		private string _addUserName;
		public virtual string AddUserName
		{
			get
			{
				return this._addUserName;
			}
			set
			{
				this._addUserName = value;
			}
		}
		
		private string _addOUGuid;
		public virtual string AddOUGuid
		{
			get
			{
				return this._addOUGuid;
			}
			set
			{
				this._addOUGuid = value;
			}
		}
		
		private string _addOUName;
		public virtual string AddOUName
		{
			get
			{
				return this._addOUName;
			}
			set
			{
				this._addOUName = value;
			}
		}
		
		private string _rowStatus1;
		public virtual string RowStatus1
		{
			get
			{
				return this._rowStatus1;
			}
			set
			{
				this._rowStatus1 = value;
			}
		}
		
		private string _rowStatus;
		public virtual string RowStatus
		{
			get
			{
				return this._rowStatus;
			}
			set
			{
				this._rowStatus = value;
			}
		}
		
	}
}
#pragma warning restore 1591
