#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Model	
{
	public partial class TB_MonitoringPoint
	{
		private string _monitoringPointUid;
		public virtual string MonitoringPointUid
		{
			get
			{
				return this._monitoringPointUid;
			}
			set
			{
				this._monitoringPointUid = value;
			}
		}
		
		private int _pointId;
		public virtual int PointId
		{
			get
			{
				return this._pointId;
			}
			set
			{
				this._pointId = value;
			}
		}
		
		private string _applicationUid;
		public virtual string ApplicationUid
		{
			get
			{
				return this._applicationUid;
			}
			set
			{
				this._applicationUid = value;
			}
		}
		
		private string _stationUid;
		public virtual string StationUid
		{
			get
			{
				return this._stationUid;
			}
			set
			{
				this._stationUid = value;
			}
		}
		
		private string _monitoringPointName;
		public virtual string MonitoringPointName
		{
			get
			{
				return this._monitoringPointName;
			}
			set
			{
				this._monitoringPointName = value;
			}
		}
		
		private string _address;
		public virtual string Address
		{
			get
			{
				return this._address;
			}
			set
			{
				this._address = value;
			}
		}
		
		private string _regionUid;
		public virtual string RegionUid
		{
			get
			{
				return this._regionUid;
			}
			set
			{
				this._regionUid = value;
			}
		}
		
		private string _monitoringRegionUid;
		public virtual string MonitoringRegionUid
		{
			get
			{
				return this._monitoringRegionUid;
			}
			set
			{
				this._monitoringRegionUid = value;
			}
		}
		
		private string _blueAlgaeRegionUid;
		public virtual string BlueAlgaeRegionUid
		{
			get
			{
				return this._blueAlgaeRegionUid;
			}
			set
			{
				this._blueAlgaeRegionUid = value;
			}
		}
		
		private string _waterStationUid;
		public virtual string WaterStationUid
		{
			get
			{
				return this._waterStationUid;
			}
			set
			{
				this._waterStationUid = value;
			}
		}
		
		private string _attachmentUid;
		public virtual string AttachmentUid
		{
			get
			{
				return this._attachmentUid;
			}
			set
			{
				this._attachmentUid = value;
			}
		}
		
		private decimal? _x;
		public virtual decimal? X
		{
			get
			{
				return this._x;
			}
			set
			{
				this._x = value;
			}
		}
		
		private decimal? _y;
		public virtual decimal? Y
		{
			get
			{
				return this._y;
			}
			set
			{
				this._y = value;
			}
		}
		
		private DateTime? _buildTime;
		public virtual DateTime? BuildTime
		{
			get
			{
				return this._buildTime;
			}
			set
			{
				this._buildTime = value;
			}
		}
		
		private string _instrumentIntegratorUid;
		public virtual string InstrumentIntegratorUid
		{
			get
			{
				return this._instrumentIntegratorUid;
			}
			set
			{
				this._instrumentIntegratorUid = value;
			}
		}
		
		private string _monitoringBussinessUid;
		public virtual string MonitoringBussinessUid
		{
			get
			{
				return this._monitoringBussinessUid;
			}
			set
			{
				this._monitoringBussinessUid = value;
			}
		}
		
		private string _enviromentFunctionUid;
		public virtual string EnviromentFunctionUid
		{
			get
			{
				return this._enviromentFunctionUid;
			}
			set
			{
				this._enviromentFunctionUid = value;
			}
		}
		
		private string _contrlUid;
		public virtual string ContrlUid
		{
			get
			{
				return this._contrlUid;
			}
			set
			{
				this._contrlUid = value;
			}
		}
		
		private string _siteTypeUid;
		public virtual string SiteTypeUid
		{
			get
			{
				return this._siteTypeUid;
			}
			set
			{
				this._siteTypeUid = value;
			}
		}
		
		private string _runStatusUid;
		public virtual string RunStatusUid
		{
			get
			{
				return this._runStatusUid;
			}
			set
			{
				this._runStatusUid = value;
			}
		}
		
		private bool? _isReferencePoint;
		public virtual bool? IsReferencePoint
		{
			get
			{
				return this._isReferencePoint;
			}
			set
			{
				this._isReferencePoint = value;
			}
		}
		
		private bool? _showOrNot;
		public virtual bool? ShowOrNot
		{
			get
			{
				return this._showOrNot;
			}
			set
			{
				this._showOrNot = value;
			}
		}
		
		private bool? _enableOrNot;
		public virtual bool? EnableOrNot
		{
			get
			{
				return this._enableOrNot;
			}
			set
			{
				this._enableOrNot = value;
			}
		}
		
		private int? _orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this._orderByNum;
			}
			set
			{
				this._orderByNum = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private string _creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this._creatUser;
			}
			set
			{
				this._creatUser = value;
			}
		}
		
		private DateTime? _creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this._creatDateTime;
			}
			set
			{
				this._creatDateTime = value;
			}
		}
		
		private string _updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this._updateUser;
			}
			set
			{
				this._updateUser = value;
			}
		}
		
		private DateTime? _updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this._updateDateTime;
			}
			set
			{
				this._updateDateTime = value;
			}
		}
		
		private string _operatorsUid;
		public virtual string OperatorsUid
		{
			get
			{
				return this._operatorsUid;
			}
			set
			{
				this._operatorsUid = value;
			}
		}
		
		private decimal? _baiduX;
		public virtual decimal? BaiduX
		{
			get
			{
				return this._baiduX;
			}
			set
			{
				this._baiduX = value;
			}
		}
		
		private decimal? _baiduY;
		public virtual decimal? BaiduY
		{
			get
			{
				return this._baiduY;
			}
			set
			{
				this._baiduY = value;
			}
		}
		
		private decimal? _customX;
		public virtual decimal? CustomX
		{
			get
			{
				return this._customX;
			}
			set
			{
				this._customX = value;
			}
		}
		
		private decimal? _customY;
		public virtual decimal? CustomY
		{
			get
			{
				return this._customY;
			}
			set
			{
				this._customY = value;
			}
		}
		
		private int? _bluedOrderNUm;
		public virtual int? BluedOrderNUm
		{
			get
			{
				return this._bluedOrderNUm;
			}
			set
			{
				this._bluedOrderNUm = value;
			}
		}
		
		private int? _pointIdBefore;
		public virtual int? PointIdBefore
		{
			get
			{
				return this._pointIdBefore;
			}
			set
			{
				this._pointIdBefore = value;
			}
		}
		
	}
}
#pragma warning restore 1591
