#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.MonitoringBusiness;
using SmartEP.Core.Interfaces;

namespace SmartEP.DomainModel.MonitoringBusiness	
{
    public partial class MonitoringBusinessModel : OpenAccessContext, IMonitoringBusinessModelUnitOfWork, ICustomOrmContext
	{
		private static string connectionStringName = @"AMS_MonitoringBusinessConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("MonitoringBusinessModel.rlinq");
		
		public MonitoringBusinessModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public MonitoringBusinessModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public MonitoringBusinessModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public MonitoringBusinessModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public MonitoringBusinessModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<ReportSamplingRateByHourEntity> ReportSamplingRateByHourEntities 
		{
			get
			{
				return this.GetAll<ReportSamplingRateByHourEntity>();
			}
		}
		
		public IQueryable<ReportSamplingRateByDayEntity> ReportSamplingRateByDayEntities 
		{
			get
			{
				return this.GetAll<ReportSamplingRateByDayEntity>();
			}
		}
		
		public IQueryable<ReportQualifiedRateByHourEntity> ReportQualifiedRateByHourEntities 
		{
			get
			{
				return this.GetAll<ReportQualifiedRateByHourEntity>();
			}
		}
		
		public IQueryable<ReportQualifiedRateByDayEntity> ReportQualifiedRateByDayEntities 
		{
			get
			{
				return this.GetAll<ReportQualifiedRateByDayEntity>();
			}
		}
		
		public IQueryable<OperationLogEntity> OperationLogEntities 
		{
			get
			{
				return this.GetAll<OperationLogEntity>();
			}
		}
		
		public IQueryable<ELMAHEntity> ELMAHEntities 
		{
			get
			{
				return this.GetAll<ELMAHEntity>();
			}
		}
		
		public IQueryable<DataSamplingConditionEntity> DataSamplingConditionEntities 
		{
			get
			{
				return this.GetAll<DataSamplingConditionEntity>();
			}
		}
		
		public IQueryable<AuditStatusMappingEntity> AuditStatusMappingEntities 
		{
			get
			{
				return this.GetAll<AuditStatusMappingEntity>();
			}
		}
		
		public IQueryable<AuditStatusForDayEntity> AuditStatusForDayEntities 
		{
			get
			{
				return this.GetAll<AuditStatusForDayEntity>();
			}
		}
		
		public IQueryable<AuditMonitoringPointPollutantEntity> AuditMonitoringPointPollutantEntities 
		{
			get
			{
				return this.GetAll<AuditMonitoringPointPollutantEntity>();
			}
		}
		
		public IQueryable<AuditMonitoringPointEntity> AuditMonitoringPointEntities 
		{
			get
			{
				return this.GetAll<AuditMonitoringPointEntity>();
			}
		}
		
		public IQueryable<AuditWaterInfectantByHourEntity> AuditWaterInfectantByHourEntities 
		{
			get
			{
				return this.GetAll<AuditWaterInfectantByHourEntity>();
			}
		}
		
		public IQueryable<AuditAirLogEntity> AuditAirLogEntities 
		{
			get
			{
				return this.GetAll<AuditAirLogEntity>();
			}
		}
		
		public IQueryable<AuditAirInfectantByMinuteEntity> AuditAirInfectantByMinuteEntities 
		{
			get
			{
				return this.GetAll<AuditAirInfectantByMinuteEntity>();
			}
		}
		
		public IQueryable<AuditAirInfectantByHourEntity> AuditAirInfectantByHourEntities 
		{
			get
			{
				return this.GetAll<AuditAirInfectantByHourEntity>();
			}
		}
		
		public IQueryable<AuditWaterLogEntity> AuditWaterLogEntities 
		{
			get
			{
				return this.GetAll<AuditWaterLogEntity>();
			}
		}
		
		public IQueryable<AuditWaterInfectantByMinuteEntity> AuditWaterInfectantByMinuteEntities 
		{
			get
			{
				return this.GetAll<AuditWaterInfectantByMinuteEntity>();
			}
		}
		
		public IQueryable<RealSampleEntity> RealSampleEntities 
		{
			get
			{
				return this.GetAll<RealSampleEntity>();
			}
		}
		
		public IQueryable<CustomDatumEntity> CustomDatumEntities 
		{
			get
			{
				return this.GetAll<CustomDatumEntity>();
			}
		}
		
		public IQueryable<StandardSolutionCheckEntity> StandardSolutionCheckEntities 
		{
			get
			{
				return this.GetAll<StandardSolutionCheckEntity>();
			}
		}
		
		public IQueryable<TaskConfigEntity> TaskConfigEntities 
		{
			get
			{
				return this.GetAll<TaskConfigEntity>();
			}
		}
		
		public IQueryable<ScrappedEntity> ScrappedEntities 
		{
			get
			{
				return this.GetAll<ScrappedEntity>();
			}
		}
		
		public IQueryable<DrySeasonReportEntity> DrySeasonReportEntities 
		{
			get
			{
				return this.GetAll<DrySeasonReportEntity>();
			}
		}
		
		public IQueryable<BlueAlgaeEarlyWarningMonitoringEntity> BlueAlgaeEarlyWarningMonitoringEntities 
		{
			get
			{
				return this.GetAll<BlueAlgaeEarlyWarningMonitoringEntity>();
			}
		}
		
		public IQueryable<AuditReasonEntity> AuditReasonEntities 
		{
			get
			{
				return this.GetAll<AuditReasonEntity>();
			}
		}
		
		public IQueryable<MaintainInstrumentEntity> MaintainInstrumentEntities 
		{
			get
			{
				return this.GetAll<MaintainInstrumentEntity>();
			}
		}
		
		public IQueryable<WaterMonthRunReportSettingEntity> WaterMonthRunReportSettingEntities 
		{
			get
			{
				return this.GetAll<WaterMonthRunReportSettingEntity>();
			}
		}
		
		public IQueryable<ReportLogEntity> ReportLogEntities 
		{
			get
			{
				return this.GetAll<ReportLogEntity>();
			}
		}
		
		public IQueryable<DutyEntity> DutyEntities 
		{
			get
			{
				return this.GetAll<DutyEntity>();
			}
		}
		
		public IQueryable<AutoMonitoringMonthSummaryEntity> AutoMonitoringMonthSummaryEntities 
		{
			get
			{
				return this.GetAll<AutoMonitoringMonthSummaryEntity>();
			}
		}
		
		public IQueryable<V_DataSamplingConditionEntity> V_DataSamplingConditionEntities 
		{
			get
			{
				return this.GetAll<V_DataSamplingConditionEntity>();
			}
		}
		
		public IQueryable<DayReportManualEntity> DayReportManualEntities 
		{
			get
			{
				return this.GetAll<DayReportManualEntity>();
			}
		}
		
		public IQueryable<DayReportBlueAlgaeEntity> DayReportBlueAlgaeEntities 
		{
			get
			{
				return this.GetAll<DayReportBlueAlgaeEntity>();
			}
		}
		
		public IQueryable<AirHourReportEntity> AirHourReportEntities 
		{
			get
			{
				return this.GetAll<AirHourReportEntity>();
			}
		}
		
		public IQueryable<AirYearReportEntity> AirYearReportEntities 
		{
			get
			{
				return this.GetAll<AirYearReportEntity>();
			}
		}
		
		public IQueryable<AirWeekReportEntity> AirWeekReportEntities 
		{
			get
			{
				return this.GetAll<AirWeekReportEntity>();
			}
		}
		
		public IQueryable<AirSeasonReportEntity> AirSeasonReportEntities 
		{
			get
			{
				return this.GetAll<AirSeasonReportEntity>();
			}
		}
		
		public IQueryable<RegionDayAQIReportEntity> RegionDayAQIReportEntities 
		{
			get
			{
				return this.GetAll<RegionDayAQIReportEntity>();
			}
		}
		
		public IQueryable<RegionDayAPIReportEntity> RegionDayAPIReportEntities 
		{
			get
			{
				return this.GetAll<RegionDayAPIReportEntity>();
			}
		}
		
		public IQueryable<AirMonthReportEntity> AirMonthReportEntities 
		{
			get
			{
				return this.GetAll<AirMonthReportEntity>();
			}
		}
		
		public IQueryable<DustHazeDayEntity> DustHazeDayEntities 
		{
			get
			{
				return this.GetAll<DustHazeDayEntity>();
			}
		}
		
		public IQueryable<AirDayReportEntity> AirDayReportEntities 
		{
			get
			{
				return this.GetAll<AirDayReportEntity>();
			}
		}
		
		public IQueryable<AirCalibrationReportEntity> AirCalibrationReportEntities 
		{
			get
			{
				return this.GetAll<AirCalibrationReportEntity>();
			}
		}
		
		public IQueryable<WeatherForcastEntity> WeatherForcastEntities 
		{
			get
			{
				return this.GetAll<WeatherForcastEntity>();
			}
		}
		
		public IQueryable<RegionHourAQIEntity> RegionHourAQIEntities 
		{
			get
			{
				return this.GetAll<RegionHourAQIEntity>();
			}
		}
		
		public IQueryable<RealTimeHourEntity> RealTimeHourEntities 
		{
			get
			{
				return this.GetAll<RealTimeHourEntity>();
			}
		}
		
		public IQueryable<HourAQIEntity> HourAQIEntities 
		{
			get
			{
				return this.GetAll<HourAQIEntity>();
			}
		}
		
		public IQueryable<HourAPIEntity> HourAPIEntities 
		{
			get
			{
				return this.GetAll<HourAPIEntity>();
			}
		}
		
		public IQueryable<DayAQIEntity> DayAQIEntities 
		{
			get
			{
				return this.GetAll<DayAQIEntity>();
			}
		}
		
		public IQueryable<DayAPIEntity> DayAPIEntities 
		{
			get
			{
				return this.GetAll<DayAPIEntity>();
			}
		}
		
		public IQueryable<AQIForcastWarningReportEntity> AQIForcastWarningReportEntities 
		{
			get
			{
				return this.GetAll<AQIForcastWarningReportEntity>();
			}
		}
		
		public IQueryable<AQIForcastDescEntity> AQIForcastDescEntities 
		{
			get
			{
				return this.GetAll<AQIForcastDescEntity>();
			}
		}
		
		public IQueryable<AQIForcastConsultationSheetEntity> AQIForcastConsultationSheetEntities 
		{
			get
			{
				return this.GetAll<AQIForcastConsultationSheetEntity>();
			}
		}
		
		public IQueryable<AQIForcastEntity> AQIForcastEntities 
		{
			get
			{
				return this.GetAll<AQIForcastEntity>();
			}
		}
		
		public IQueryable<WaterYearReportEntity> WaterYearReportEntities 
		{
			get
			{
				return this.GetAll<WaterYearReportEntity>();
			}
		}
		
		public IQueryable<WaterWeekReportEntity> WaterWeekReportEntities 
		{
			get
			{
				return this.GetAll<WaterWeekReportEntity>();
			}
		}
		
		public IQueryable<WaterSeasonReportEntity> WaterSeasonReportEntities 
		{
			get
			{
				return this.GetAll<WaterSeasonReportEntity>();
			}
		}
		
		public IQueryable<WaterMonthReportEntity> WaterMonthReportEntities 
		{
			get
			{
				return this.GetAll<WaterMonthReportEntity>();
			}
		}
		
		public IQueryable<WaterHourReportEntity> WaterHourReportEntities 
		{
			get
			{
				return this.GetAll<WaterHourReportEntity>();
			}
		}
		
		public IQueryable<WaterDayReportEntity> WaterDayReportEntities 
		{
			get
			{
				return this.GetAll<WaterDayReportEntity>();
			}
		}
		
		public IQueryable<WaterCalibrationReportEntity> WaterCalibrationReportEntities 
		{
			get
			{
				return this.GetAll<WaterCalibrationReportEntity>();
			}
		}
		
		public IQueryable<AirHourReportForUpLoadEntity> AirHourReportForUpLoadEntities 
		{
			get
			{
				return this.GetAll<AirHourReportForUpLoadEntity>();
			}
		}
		
		public IQueryable<AirHourReportForUpLoadSZEntity> AirHourReportForUpLoadSZEntities 
		{
			get
			{
				return this.GetAll<AirHourReportForUpLoadSZEntity>();
			}
		}
		
		public IQueryable<OM_TaskItemConfigEntity> OM_TaskItemConfigEntities 
		{
			get
			{
				return this.GetAll<OM_TaskItemConfigEntity>();
			}
		}
		
		public IQueryable<OM_DeviceRepairDetailEntity> OM_DeviceRepairDetailEntities 
		{
			get
			{
				return this.GetAll<OM_DeviceRepairDetailEntity>();
			}
		}
		
		public IQueryable<OM_DeviceRepairEntity> OM_DeviceRepairEntities 
		{
			get
			{
				return this.GetAll<OM_DeviceRepairEntity>();
			}
		}
		
		public IQueryable<OM_TaskItemDatumEntity> OM_TaskItemDatumEntities 
		{
			get
			{
				return this.GetAll<OM_TaskItemDatumEntity>();
			}
		}
		
		public IQueryable<InstrumentOPDatumEntity> InstrumentOPDatumEntities 
		{
			get
			{
				return this.GetAll<InstrumentOPDatumEntity>();
			}
		}
		
		public IQueryable<AuditOperatorSettingEntity> AuditOperatorSettingEntities 
		{
			get
			{
				return this.GetAll<AuditOperatorSettingEntity>();
			}
		}
		
		public IQueryable<V_AuditOperatorSettingEntity> V_AuditOperatorSettingEntities 
		{
			get
			{
				return this.GetAll<V_AuditOperatorSettingEntity>();
			}
		}
		
		public IQueryable<AuditWaterStatusForHourEntity> AuditWaterStatusForHourEntities 
		{
			get
			{
				return this.GetAll<AuditWaterStatusForHourEntity>();
			}
		}
		
		public IQueryable<AuditAirStatusForHourEntity> AuditAirStatusForHourEntities 
		{
			get
			{
				return this.GetAll<AuditAirStatusForHourEntity>();
			}
		}
		
		public IQueryable<QC_Report_PMSharp5030FlowCheckCaliEntity> QC_Report_PMSharp5030FlowCheckCaliEntities 
		{
			get
			{
				return this.GetAll<QC_Report_PMSharp5030FlowCheckCaliEntity>();
			}
		}
		
		public IQueryable<QC_Report_PMTEOMRPFlowCheckCaliEntity> QC_Report_PMTEOMRPFlowCheckCaliEntities 
		{
			get
			{
				return this.GetAll<QC_Report_PMTEOMRPFlowCheckCaliEntity>();
			}
		}
		
		public IQueryable<InstrumentDataOnlineEntity> InstrumentDataOnlineEntities 
		{
			get
			{
				return this.GetAll<InstrumentDataOnlineEntity>();
			}
		}
		
		public IQueryable<RPT_AQIForecastEntity> RPT_AQIForecastEntities 
		{
			get
			{
				return this.GetAll<RPT_AQIForecastEntity>();
			}
		}
		
		public IQueryable<DataOnlineEntity> DataOnlineEntities 
		{
			get
			{
				return this.GetAll<DataOnlineEntity>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of MonitoringBusinessModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of MonitoringBusinessModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IMonitoringBusinessModelUnitOfWork : IUnitOfWork
	{
		IQueryable<ReportSamplingRateByHourEntity> ReportSamplingRateByHourEntities
		{
			get;
		}
		IQueryable<ReportSamplingRateByDayEntity> ReportSamplingRateByDayEntities
		{
			get;
		}
		IQueryable<ReportQualifiedRateByHourEntity> ReportQualifiedRateByHourEntities
		{
			get;
		}
		IQueryable<ReportQualifiedRateByDayEntity> ReportQualifiedRateByDayEntities
		{
			get;
		}
		IQueryable<OperationLogEntity> OperationLogEntities
		{
			get;
		}
		IQueryable<ELMAHEntity> ELMAHEntities
		{
			get;
		}
		IQueryable<DataSamplingConditionEntity> DataSamplingConditionEntities
		{
			get;
		}
		IQueryable<AuditStatusMappingEntity> AuditStatusMappingEntities
		{
			get;
		}
		IQueryable<AuditStatusForDayEntity> AuditStatusForDayEntities
		{
			get;
		}
		IQueryable<AuditMonitoringPointPollutantEntity> AuditMonitoringPointPollutantEntities
		{
			get;
		}
		IQueryable<AuditMonitoringPointEntity> AuditMonitoringPointEntities
		{
			get;
		}
		IQueryable<AuditWaterInfectantByHourEntity> AuditWaterInfectantByHourEntities
		{
			get;
		}
		IQueryable<AuditAirLogEntity> AuditAirLogEntities
		{
			get;
		}
		IQueryable<AuditAirInfectantByMinuteEntity> AuditAirInfectantByMinuteEntities
		{
			get;
		}
		IQueryable<AuditAirInfectantByHourEntity> AuditAirInfectantByHourEntities
		{
			get;
		}
		IQueryable<AuditWaterLogEntity> AuditWaterLogEntities
		{
			get;
		}
		IQueryable<AuditWaterInfectantByMinuteEntity> AuditWaterInfectantByMinuteEntities
		{
			get;
		}
		IQueryable<RealSampleEntity> RealSampleEntities
		{
			get;
		}
		IQueryable<CustomDatumEntity> CustomDatumEntities
		{
			get;
		}
		IQueryable<StandardSolutionCheckEntity> StandardSolutionCheckEntities
		{
			get;
		}
		IQueryable<TaskConfigEntity> TaskConfigEntities
		{
			get;
		}
		IQueryable<ScrappedEntity> ScrappedEntities
		{
			get;
		}
		IQueryable<DrySeasonReportEntity> DrySeasonReportEntities
		{
			get;
		}
		IQueryable<BlueAlgaeEarlyWarningMonitoringEntity> BlueAlgaeEarlyWarningMonitoringEntities
		{
			get;
		}
		IQueryable<AuditReasonEntity> AuditReasonEntities
		{
			get;
		}
		IQueryable<MaintainInstrumentEntity> MaintainInstrumentEntities
		{
			get;
		}
		IQueryable<WaterMonthRunReportSettingEntity> WaterMonthRunReportSettingEntities
		{
			get;
		}
		IQueryable<ReportLogEntity> ReportLogEntities
		{
			get;
		}
		IQueryable<DutyEntity> DutyEntities
		{
			get;
		}
		IQueryable<AutoMonitoringMonthSummaryEntity> AutoMonitoringMonthSummaryEntities
		{
			get;
		}
		IQueryable<V_DataSamplingConditionEntity> V_DataSamplingConditionEntities
		{
			get;
		}
		IQueryable<DayReportManualEntity> DayReportManualEntities
		{
			get;
		}
		IQueryable<DayReportBlueAlgaeEntity> DayReportBlueAlgaeEntities
		{
			get;
		}
		IQueryable<AirHourReportEntity> AirHourReportEntities
		{
			get;
		}
		IQueryable<AirYearReportEntity> AirYearReportEntities
		{
			get;
		}
		IQueryable<AirWeekReportEntity> AirWeekReportEntities
		{
			get;
		}
		IQueryable<AirSeasonReportEntity> AirSeasonReportEntities
		{
			get;
		}
		IQueryable<RegionDayAQIReportEntity> RegionDayAQIReportEntities
		{
			get;
		}
		IQueryable<RegionDayAPIReportEntity> RegionDayAPIReportEntities
		{
			get;
		}
		IQueryable<AirMonthReportEntity> AirMonthReportEntities
		{
			get;
		}
		IQueryable<DustHazeDayEntity> DustHazeDayEntities
		{
			get;
		}
		IQueryable<AirDayReportEntity> AirDayReportEntities
		{
			get;
		}
		IQueryable<AirCalibrationReportEntity> AirCalibrationReportEntities
		{
			get;
		}
		IQueryable<WeatherForcastEntity> WeatherForcastEntities
		{
			get;
		}
		IQueryable<RegionHourAQIEntity> RegionHourAQIEntities
		{
			get;
		}
		IQueryable<RealTimeHourEntity> RealTimeHourEntities
		{
			get;
		}
		IQueryable<HourAQIEntity> HourAQIEntities
		{
			get;
		}
		IQueryable<HourAPIEntity> HourAPIEntities
		{
			get;
		}
		IQueryable<DayAQIEntity> DayAQIEntities
		{
			get;
		}
		IQueryable<DayAPIEntity> DayAPIEntities
		{
			get;
		}
		IQueryable<AQIForcastWarningReportEntity> AQIForcastWarningReportEntities
		{
			get;
		}
		IQueryable<AQIForcastDescEntity> AQIForcastDescEntities
		{
			get;
		}
		IQueryable<AQIForcastConsultationSheetEntity> AQIForcastConsultationSheetEntities
		{
			get;
		}
		IQueryable<AQIForcastEntity> AQIForcastEntities
		{
			get;
		}
		IQueryable<WaterYearReportEntity> WaterYearReportEntities
		{
			get;
		}
		IQueryable<WaterWeekReportEntity> WaterWeekReportEntities
		{
			get;
		}
		IQueryable<WaterSeasonReportEntity> WaterSeasonReportEntities
		{
			get;
		}
		IQueryable<WaterMonthReportEntity> WaterMonthReportEntities
		{
			get;
		}
		IQueryable<WaterHourReportEntity> WaterHourReportEntities
		{
			get;
		}
		IQueryable<WaterDayReportEntity> WaterDayReportEntities
		{
			get;
		}
		IQueryable<WaterCalibrationReportEntity> WaterCalibrationReportEntities
		{
			get;
		}
		IQueryable<AirHourReportForUpLoadEntity> AirHourReportForUpLoadEntities
		{
			get;
		}
		IQueryable<AirHourReportForUpLoadSZEntity> AirHourReportForUpLoadSZEntities
		{
			get;
		}
		IQueryable<OM_TaskItemConfigEntity> OM_TaskItemConfigEntities
		{
			get;
		}
		IQueryable<OM_DeviceRepairDetailEntity> OM_DeviceRepairDetailEntities
		{
			get;
		}
		IQueryable<OM_DeviceRepairEntity> OM_DeviceRepairEntities
		{
			get;
		}
		IQueryable<OM_TaskItemDatumEntity> OM_TaskItemDatumEntities
		{
			get;
		}
		IQueryable<InstrumentOPDatumEntity> InstrumentOPDatumEntities
		{
			get;
		}
		IQueryable<AuditOperatorSettingEntity> AuditOperatorSettingEntities
		{
			get;
		}
		IQueryable<V_AuditOperatorSettingEntity> V_AuditOperatorSettingEntities
		{
			get;
		}
		IQueryable<AuditWaterStatusForHourEntity> AuditWaterStatusForHourEntities
		{
			get;
		}
		IQueryable<AuditAirStatusForHourEntity> AuditAirStatusForHourEntities
		{
			get;
		}
		IQueryable<QC_Report_PMSharp5030FlowCheckCaliEntity> QC_Report_PMSharp5030FlowCheckCaliEntities
		{
			get;
		}
		IQueryable<QC_Report_PMTEOMRPFlowCheckCaliEntity> QC_Report_PMTEOMRPFlowCheckCaliEntities
		{
			get;
		}
		IQueryable<InstrumentDataOnlineEntity> InstrumentDataOnlineEntities
		{
			get;
		}
		IQueryable<RPT_AQIForecastEntity> RPT_AQIForecastEntities
		{
			get;
		}
		IQueryable<DataOnlineEntity> DataOnlineEntities
		{
			get;
		}
	}
}
#pragma warning restore 1591
