#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Model	
{
	public partial class DT_ConfigIDInfo
	{
		private long _id;
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private long? _maxid;
		public virtual long? Maxid
		{
			get
			{
				return this._maxid;
			}
			set
			{
				this._maxid = value;
			}
		}
		
		private string _memo;
		public virtual string Memo
		{
			get
			{
				return this._memo;
			}
			set
			{
				this._memo = value;
			}
		}
		
		private DateTime? _createdatetime;
		public virtual DateTime? Createdatetime
		{
			get
			{
				return this._createdatetime;
			}
			set
			{
				this._createdatetime = value;
			}
		}
		
		private DateTime? _updatedatetime;
		public virtual DateTime? Updatedatetime
		{
			get
			{
				return this._updatedatetime;
			}
			set
			{
				this._updatedatetime = value;
			}
		}
		
	}
}
#pragma warning restore 1591
