#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Model	
{
	public partial class InstrumentDataOnline
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _instrumentUid;
		public virtual string InstrumentUid
		{
			get
			{
				return this._instrumentUid;
			}
			set
			{
				this._instrumentUid = value;
			}
		}
		
		private string _instrumentName;
		public virtual string InstrumentName
		{
			get
			{
				return this._instrumentName;
			}
			set
			{
				this._instrumentName = value;
			}
		}
		
		private string _dataTypeUid;
		public virtual string DataTypeUid
		{
			get
			{
				return this._dataTypeUid;
			}
			set
			{
				this._dataTypeUid = value;
			}
		}
		
		private int? _isOnline;
		public virtual int? IsOnline
		{
			get
			{
				return this._isOnline;
			}
			set
			{
				this._isOnline = value;
			}
		}
		
		private DateTime? _newDataTime;
		public virtual DateTime? NewDataTime
		{
			get
			{
				return this._newDataTime;
			}
			set
			{
				this._newDataTime = value;
			}
		}
		
		private int? _offLineTime;
		public virtual int? OffLineTime
		{
			get
			{
				return this._offLineTime;
			}
			set
			{
				this._offLineTime = value;
			}
		}
		
	}
}
#pragma warning restore 1591
