#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Model	
{
	public partial class V_CodeDictionary
	{
		private string _updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this._updateUser;
			}
			set
			{
				this._updateUser = value;
			}
		}
		
		private DateTime? _updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this._updateDateTime;
			}
			set
			{
				this._updateDateTime = value;
			}
		}
		
		private int? _sortNumber;
		public virtual int? SortNumber
		{
			get
			{
				return this._sortNumber;
			}
			set
			{
				this._sortNumber = value;
			}
		}
		
		private int? _orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this._orderByNum;
			}
			set
			{
				this._orderByNum = value;
			}
		}
		
		private string _mainGuid;
		public virtual string MainGuid
		{
			get
			{
				return this._mainGuid;
			}
			set
			{
				this._mainGuid = value;
			}
		}
		
		private string _itemText;
		public virtual string ItemText
		{
			get
			{
				return this._itemText;
			}
			set
			{
				this._itemText = value;
			}
		}
		
		private string _itemGuid;
		public virtual string ItemGuid
		{
			get
			{
				return this._itemGuid;
			}
			set
			{
				this._itemGuid = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private string _creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this._creatUser;
			}
			set
			{
				this._creatUser = value;
			}
		}
		
		private DateTime? _creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this._creatDateTime;
			}
			set
			{
				this._creatDateTime = value;
			}
		}
		
		private string _codeName;
		public virtual string CodeName
		{
			get
			{
				return this._codeName;
			}
			set
			{
				this._codeName = value;
			}
		}
		
		private string _codeDictionaryName;
		public virtual string CodeDictionaryName
		{
			get
			{
				return this._codeDictionaryName;
			}
			set
			{
				this._codeDictionaryName = value;
			}
		}
		
	}
}
#pragma warning restore 1591
