//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RadSchedulerRecurrenceEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RadSchedulerRecurrenceEditor() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadSchedulerRecurrenceEditor", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string CalendarCancel {
            get {
                return ResourceManager.GetString("CalendarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string CalendarOK {
            get {
                return ResourceManager.GetString("CalendarOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        internal static string CalendarToday {
            get {
                return ResourceManager.GetString("CalendarToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Daily 的本地化字符串。
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Day 的本地化字符串。
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 day(s) 的本地化字符串。
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End after 的本地化字符串。
        /// </summary>
        internal static string EndAfter {
            get {
                return ResourceManager.GetString("EndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End by 的本地化字符串。
        /// </summary>
        internal static string EndByThisDate {
            get {
                return ResourceManager.GetString("EndByThisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every 的本地化字符串。
        /// </summary>
        internal static string Every {
            get {
                return ResourceManager.GetString("Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every weekday 的本地化字符串。
        /// </summary>
        internal static string EveryWeekday {
            get {
                return ResourceManager.GetString("EveryWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 first 的本地化字符串。
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fourth 的本地化字符串。
        /// </summary>
        internal static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hourly 的本地化字符串。
        /// </summary>
        internal static string Hourly {
            get {
                return ResourceManager.GetString("Hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hour(s) 的本地化字符串。
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 last 的本地化字符串。
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 day 的本地化字符串。
        /// </summary>
        internal static string MaskDay {
            get {
                return ResourceManager.GetString("MaskDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 weekday 的本地化字符串。
        /// </summary>
        internal static string MaskWeekday {
            get {
                return ResourceManager.GetString("MaskWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 weekend day 的本地化字符串。
        /// </summary>
        internal static string MaskWeekendDay {
            get {
                return ResourceManager.GetString("MaskWeekendDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monthly 的本地化字符串。
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 month(s) 的本地化字符串。
        /// </summary>
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No end date 的本地化字符串。
        /// </summary>
        internal static string NoEndDate {
            get {
                return ResourceManager.GetString("NoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 occurrences 的本地化字符串。
        /// </summary>
        internal static string Occurrences {
            get {
                return ResourceManager.GetString("Occurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of 的本地化字符串。
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of every 的本地化字符串。
        /// </summary>
        internal static string OfEvery {
            get {
                return ResourceManager.GetString("OfEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recur every 的本地化字符串。
        /// </summary>
        internal static string RecurEvery {
            get {
                return ResourceManager.GetString("RecurEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recurrence 的本地化字符串。
        /// </summary>
        internal static string Recurrence {
            get {
                return ResourceManager.GetString("Recurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please do not remove this key. 的本地化字符串。
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 second 的本地化字符串。
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The 的本地化字符串。
        /// </summary>
        internal static string The {
            get {
                return ResourceManager.GetString("The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 third 的本地化字符串。
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weekly 的本地化字符串。
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 week(s) on 的本地化字符串。
        /// </summary>
        internal static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yearly 的本地化字符串。
        /// </summary>
        internal static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
    }
}
