#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.BaseData;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class CustomPollutantGroupEntity : IBasicInfoEntityProperty
	{
		private string m_customPollutantCategoryUid;
		public virtual string CustomPollutantCategoryUid
		{
			get
			{
				return this.m_customPollutantCategoryUid;
			}
			set
			{
				this.m_customPollutantCategoryUid = value;
			}
		}
		
		private string m_customPollutantGroupUid;
		public virtual string CustomPollutantGroupUid
		{
			get
			{
				return this.m_customPollutantGroupUid;
			}
			set
			{
				this.m_customPollutantGroupUid = value;
			}
		}
		
		private string m_usedPollutantUid;
		public virtual string UsedPollutantUid
		{
			get
			{
				return this.m_usedPollutantUid;
			}
			set
			{
				this.m_usedPollutantUid = value;
			}
		}
		
		private bool? m_showOrNot;
		public virtual bool? ShowOrNot
		{
			get
			{
				return this.m_showOrNot;
			}
			set
			{
				this.m_showOrNot = value;
			}
		}
		
		private string m_spell;
		public virtual string Spell
		{
			get
			{
				return this.m_spell;
			}
			set
			{
				this.m_spell = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private UsedPollutantEntity m_usedPollutantEntity;
		public virtual UsedPollutantEntity UsedPollutantEntity
		{
			get
			{
				return this.m_usedPollutantEntity;
			}
			set
			{
				this.m_usedPollutantEntity = value;
			}
		}
		
		private CustomPollutantCategoryEntity m_customPollutantCategoryEntity;
		public virtual CustomPollutantCategoryEntity CustomPollutantCategoryEntity
		{
			get
			{
				return this.m_customPollutantCategoryEntity;
			}
			set
			{
				this.m_customPollutantCategoryEntity = value;
			}
		}
		
	}
}
#pragma warning restore 1591
