#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.AirMonitoringBusiness;

namespace SmartEP.DomainModel.AirMonitoringBusiness	
{
	public partial class RegionDayAPIReportEntity : IAirMonitoringBusinessEntityProperty
	{
		private string m_cityDayAPIUid;
		public virtual string CityDayAPIUid
		{
			get
			{
				return this.m_cityDayAPIUid;
			}
			set
			{
				this.m_cityDayAPIUid = value;
			}
		}
		
		private byte[] m_monitoringRegionUid;
		public virtual byte[] MonitoringRegionUid
		{
			get
			{
				return this.m_monitoringRegionUid;
			}
			set
			{
				this.m_monitoringRegionUid = value;
			}
		}
		
		private DateTime? m_reportDateTime;
		public virtual DateTime? ReportDateTime
		{
			get
			{
				return this.m_reportDateTime;
			}
			set
			{
				this.m_reportDateTime = value;
			}
		}
		
		private string m_reportType;
		public virtual string ReportType
		{
			get
			{
				return this.m_reportType;
			}
			set
			{
				this.m_reportType = value;
			}
		}
		
		private string m_sO2;
		public virtual string SO2
		{
			get
			{
				return this.m_sO2;
			}
			set
			{
				this.m_sO2 = value;
			}
		}
		
		private string m_sO2_IAPI;
		public virtual string SO2_IAPI
		{
			get
			{
				return this.m_sO2_IAPI;
			}
			set
			{
				this.m_sO2_IAPI = value;
			}
		}
		
		private string m_nO2;
		public virtual string NO2
		{
			get
			{
				return this.m_nO2;
			}
			set
			{
				this.m_nO2 = value;
			}
		}
		
		private string m_nO2_IAPI;
		public virtual string NO2_IAPI
		{
			get
			{
				return this.m_nO2_IAPI;
			}
			set
			{
				this.m_nO2_IAPI = value;
			}
		}
		
		private string m_pM10;
		public virtual string PM10
		{
			get
			{
				return this.m_pM10;
			}
			set
			{
				this.m_pM10 = value;
			}
		}
		
		private string m_pM10_IAPI;
		public virtual string PM10_IAPI
		{
			get
			{
				return this.m_pM10_IAPI;
			}
			set
			{
				this.m_pM10_IAPI = value;
			}
		}
		
		private string m_aPI;
		public virtual string API
		{
			get
			{
				return this.m_aPI;
			}
			set
			{
				this.m_aPI = value;
			}
		}
		
		private string m_aPI_FactorCode;
		public virtual string API_FactorCode
		{
			get
			{
				return this.m_aPI_FactorCode;
			}
			set
			{
				this.m_aPI_FactorCode = value;
			}
		}
		
		private string m_aPI_FactorName;
		public virtual string API_FactorName
		{
			get
			{
				return this.m_aPI_FactorName;
			}
			set
			{
				this.m_aPI_FactorName = value;
			}
		}
		
		private string m_aPI_FactorSName;
		public virtual string API_FactorSName
		{
			get
			{
				return this.m_aPI_FactorSName;
			}
			set
			{
				this.m_aPI_FactorSName = value;
			}
		}
		
		private string m_range;
		public virtual string Range
		{
			get
			{
				return this.m_range;
			}
			set
			{
				this.m_range = value;
			}
		}
		
		private string m_grade;
		public virtual string Grade
		{
			get
			{
				return this.m_grade;
			}
			set
			{
				this.m_grade = value;
			}
		}
		
		private string m_roman;
		public virtual string Roman
		{
			get
			{
				return this.m_roman;
			}
			set
			{
				this.m_roman = value;
			}
		}
		
		private string m_class;
		public virtual string Class
		{
			get
			{
				return this.m_class;
			}
			set
			{
				this.m_class = value;
			}
		}
		
		private string m_healTheffect;
		public virtual string HealTheffect
		{
			get
			{
				return this.m_healTheffect;
			}
			set
			{
				this.m_healTheffect = value;
			}
		}
		
		private string m_takeStep;
		public virtual string TakeStep
		{
			get
			{
				return this.m_takeStep;
			}
			set
			{
				this.m_takeStep = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
	}
}
#pragma warning restore 1591
