#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.AirMonitoringBusiness;
using SmartEP.Core.Interfaces;

namespace SmartEP.DomainModel.AirMonitoringBusiness	
{
    public partial class AirMonitoringBusinessModel : OpenAccessContext, IAirMonitoringBusinessModelUnitOfWork, ICustomOrmContext
	{
		private static string connectionStringName = @"AMS_MonitoringBusinessConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("AirMonitoringBusinessModel.rlinq");
		
		public AirMonitoringBusinessModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public AirMonitoringBusinessModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public AirMonitoringBusinessModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public AirMonitoringBusinessModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public AirMonitoringBusinessModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<YearReportEntity> YearReportEntities 
		{
			get
			{
				return this.GetAll<YearReportEntity>();
			}
		}
		
		public IQueryable<WeekReportEntity> WeekReportEntities 
		{
			get
			{
				return this.GetAll<WeekReportEntity>();
			}
		}
		
		public IQueryable<WeatherForcastEntity> WeatherForcastEntities 
		{
			get
			{
				return this.GetAll<WeatherForcastEntity>();
			}
		}
		
		public IQueryable<SeasonReportEntity> SeasonReportEntities 
		{
			get
			{
				return this.GetAll<SeasonReportEntity>();
			}
		}
		
		public IQueryable<RegionHourAQIEntity> RegionHourAQIEntities 
		{
			get
			{
				return this.GetAll<RegionHourAQIEntity>();
			}
		}
		
		public IQueryable<RegionDayAQIReportEntity> RegionDayAQIReportEntities 
		{
			get
			{
				return this.GetAll<RegionDayAQIReportEntity>();
			}
		}
		
		public IQueryable<RegionDayAPIReportEntity> RegionDayAPIReportEntities 
		{
			get
			{
				return this.GetAll<RegionDayAPIReportEntity>();
			}
		}
		
		public IQueryable<RealTimeHourEntity> RealTimeHourEntities 
		{
			get
			{
				return this.GetAll<RealTimeHourEntity>();
			}
		}
		
		public IQueryable<MonthReportEntity> MonthReportEntities 
		{
			get
			{
				return this.GetAll<MonthReportEntity>();
			}
		}
		
		public IQueryable<HourReportEntity> HourReportEntities 
		{
			get
			{
				return this.GetAll<HourReportEntity>();
			}
		}
		
		public IQueryable<HourAQIEntity> HourAQIEntities 
		{
			get
			{
				return this.GetAll<HourAQIEntity>();
			}
		}
		
		public IQueryable<HourAPIEntity> HourAPIEntities 
		{
			get
			{
				return this.GetAll<HourAPIEntity>();
			}
		}
		
		public IQueryable<DayReportEntity> DayReportEntities 
		{
			get
			{
				return this.GetAll<DayReportEntity>();
			}
		}
		
		public IQueryable<DayAQIEntity> DayAQIEntities 
		{
			get
			{
				return this.GetAll<DayAQIEntity>();
			}
		}
		
		public IQueryable<DayAPIEntity> DayAPIEntities 
		{
			get
			{
				return this.GetAll<DayAPIEntity>();
			}
		}
		
		public IQueryable<CalibrationReportEntity> CalibrationReportEntities 
		{
			get
			{
				return this.GetAll<CalibrationReportEntity>();
			}
		}
		
		public IQueryable<AQIForcastWarningReportEntity> AQIForcastWarningReportEntities 
		{
			get
			{
				return this.GetAll<AQIForcastWarningReportEntity>();
			}
		}
		
		public IQueryable<AQIForcastDescEntity> AQIForcastDescEntities 
		{
			get
			{
				return this.GetAll<AQIForcastDescEntity>();
			}
		}
		
		public IQueryable<AQIForcastConsultationSheetEntity> AQIForcastConsultationSheetEntities 
		{
			get
			{
				return this.GetAll<AQIForcastConsultationSheetEntity>();
			}
		}
		
		public IQueryable<AQIForcastEntity> AQIForcastEntities 
		{
			get
			{
				return this.GetAll<AQIForcastEntity>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of AirMonitoringBusinessModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of AirMonitoringBusinessModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IAirMonitoringBusinessModelUnitOfWork : IUnitOfWork
	{
		IQueryable<YearReportEntity> YearReportEntities
		{
			get;
		}
		IQueryable<WeekReportEntity> WeekReportEntities
		{
			get;
		}
		IQueryable<WeatherForcastEntity> WeatherForcastEntities
		{
			get;
		}
		IQueryable<SeasonReportEntity> SeasonReportEntities
		{
			get;
		}
		IQueryable<RegionHourAQIEntity> RegionHourAQIEntities
		{
			get;
		}
		IQueryable<RegionDayAQIReportEntity> RegionDayAQIReportEntities
		{
			get;
		}
		IQueryable<RegionDayAPIReportEntity> RegionDayAPIReportEntities
		{
			get;
		}
		IQueryable<RealTimeHourEntity> RealTimeHourEntities
		{
			get;
		}
		IQueryable<MonthReportEntity> MonthReportEntities
		{
			get;
		}
		IQueryable<HourReportEntity> HourReportEntities
		{
			get;
		}
		IQueryable<HourAQIEntity> HourAQIEntities
		{
			get;
		}
		IQueryable<HourAPIEntity> HourAPIEntities
		{
			get;
		}
		IQueryable<DayReportEntity> DayReportEntities
		{
			get;
		}
		IQueryable<DayAQIEntity> DayAQIEntities
		{
			get;
		}
		IQueryable<DayAPIEntity> DayAPIEntities
		{
			get;
		}
		IQueryable<CalibrationReportEntity> CalibrationReportEntities
		{
			get;
		}
		IQueryable<AQIForcastWarningReportEntity> AQIForcastWarningReportEntities
		{
			get;
		}
		IQueryable<AQIForcastDescEntity> AQIForcastDescEntities
		{
			get;
		}
		IQueryable<AQIForcastConsultationSheetEntity> AQIForcastConsultationSheetEntities
		{
			get;
		}
		IQueryable<AQIForcastEntity> AQIForcastEntities
		{
			get;
		}
	}
}
#pragma warning restore 1591
