//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.19118
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartEP.WebService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.GISServiceSoap")]
    public interface GISServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHourDataByZJG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHourDataByZJG(string portId, string factorName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHourDataByZJG", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHourDataByZJGAsync(string portId, string factorName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPortALLDetailZJG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPortALLDetailZJG(string dataType, string portId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPortALLDetailZJG", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPortALLDetailZJGAsync(string dataType, string portId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GISServiceSoapChannel : SmartEP.WebService.ServiceReference1.GISServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GISServiceSoapClient : System.ServiceModel.ClientBase<SmartEP.WebService.ServiceReference1.GISServiceSoap>, SmartEP.WebService.ServiceReference1.GISServiceSoap {
        
        public GISServiceSoapClient() {
        }
        
        public GISServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GISServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GISServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GISServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetHourDataByZJG(string portId, string factorName) {
            return base.Channel.GetHourDataByZJG(portId, factorName);
        }
        
        public System.Threading.Tasks.Task<string> GetHourDataByZJGAsync(string portId, string factorName) {
            return base.Channel.GetHourDataByZJGAsync(portId, factorName);
        }
        
        public string GetPortALLDetailZJG(string dataType, string portId) {
            return base.Channel.GetPortALLDetailZJG(dataType, portId);
        }
        
        public System.Threading.Tasks.Task<string> GetPortALLDetailZJGAsync(string dataType, string portId) {
            return base.Channel.GetPortALLDetailZJGAsync(dataType, portId);
        }
    }
}
