#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class DT_DataTypeConfigEntity
	{
		private int m_id;
		public virtual int Id
		{
			get
			{
				return this.m_id;
			}
			set
			{
				this.m_id = value;
			}
		}
		
		private string m_rowGuid;
		public virtual string RowGuid
		{
			get
			{
				return this.m_rowGuid;
			}
			set
			{
				this.m_rowGuid = value;
			}
		}
		
		private string m_dataTypeUid;
		public virtual string DataTypeUid
		{
			get
			{
				return this.m_dataTypeUid;
			}
			set
			{
				this.m_dataTypeUid = value;
			}
		}
		
		private string m_bufferTable;
		public virtual string BufferTable
		{
			get
			{
				return this.m_bufferTable;
			}
			set
			{
				this.m_bufferTable = value;
			}
		}
		
		private string m_sYBufferTable;
		public virtual string SYBufferTable
		{
			get
			{
				return this.m_sYBufferTable;
			}
			set
			{
				this.m_sYBufferTable = value;
			}
		}
		
		private string m_originalTable;
		public virtual string OriginalTable
		{
			get
			{
				return this.m_originalTable;
			}
			set
			{
				this.m_originalTable = value;
			}
		}
		
		private string m_sYOriginalTable;
		public virtual string SYOriginalTable
		{
			get
			{
				return this.m_sYOriginalTable;
			}
			set
			{
				this.m_sYOriginalTable = value;
			}
		}
		
		private string m_preAuditTable;
		public virtual string PreAuditTable
		{
			get
			{
				return this.m_preAuditTable;
			}
			set
			{
				this.m_preAuditTable = value;
			}
		}
		
		private string m_calculateTable;
		public virtual string CalculateTable
		{
			get
			{
				return this.m_calculateTable;
			}
			set
			{
				this.m_calculateTable = value;
			}
		}
		
		private string m_auditTable;
		public virtual string AuditTable
		{
			get
			{
				return this.m_auditTable;
			}
			set
			{
				this.m_auditTable = value;
			}
		}
		
		private bool? m_enableOrNot;
		public virtual bool? EnableOrNot
		{
			get
			{
				return this.m_enableOrNot;
			}
			set
			{
				this.m_enableOrNot = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private string m_rowStatus;
		public virtual string RowStatus
		{
			get
			{
				return this.m_rowStatus;
			}
			set
			{
				this.m_rowStatus = value;
			}
		}
		
	}
}
#pragma warning restore 1591
