#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.BaseData;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class ExcessiveSolutionDetailEntity : IStandardEntityProperty
	{
		private string m_excessiveSolutionUid;
		public virtual string ExcessiveSolutionUid
		{
			get
			{
				return this.m_excessiveSolutionUid;
			}
			set
			{
				this.m_excessiveSolutionUid = value;
			}
		}
		
		private int m_id;
		public virtual int Id
		{
			get
			{
				return this.m_id;
			}
			set
			{
				this.m_id = value;
			}
		}
		
		private string m_rowGuid;
		public virtual string RowGuid
		{
			get
			{
				return this.m_rowGuid;
			}
			set
			{
				this.m_rowGuid = value;
			}
		}
		
		private string m_solutionUid;
		public virtual string SolutionUid
		{
			get
			{
				return this.m_solutionUid;
			}
			set
			{
				this.m_solutionUid = value;
			}
		}
		
		private string m_pollutantCode;
		public virtual string PollutantCode
		{
			get
			{
				return this.m_pollutantCode;
			}
			set
			{
				this.m_pollutantCode = value;
			}
		}
		
		private decimal? m_advanceLow;
		public virtual decimal? AdvanceLow
		{
			get
			{
				return this.m_advanceLow;
			}
			set
			{
				this.m_advanceLow = value;
			}
		}
		
		private decimal? m_advanceUpper;
		public virtual decimal? AdvanceUpper
		{
			get
			{
				return this.m_advanceUpper;
			}
			set
			{
				this.m_advanceUpper = value;
			}
		}
		
		private string m_advanceRange;
		public virtual string AdvanceRange
		{
			get
			{
				return this.m_advanceRange;
			}
			set
			{
				this.m_advanceRange = value;
			}
		}
		
		private decimal? m_excessiveUpper;
		public virtual decimal? ExcessiveUpper
		{
			get
			{
				return this.m_excessiveUpper;
			}
			set
			{
				this.m_excessiveUpper = value;
			}
		}
		
		private decimal? m_excessiveLow;
		public virtual decimal? ExcessiveLow
		{
			get
			{
				return this.m_excessiveLow;
			}
			set
			{
				this.m_excessiveLow = value;
			}
		}
		
		private string m_excessiveRange;
		public virtual string ExcessiveRange
		{
			get
			{
				return this.m_excessiveRange;
			}
			set
			{
				this.m_excessiveRange = value;
			}
		}
		
		private string m_replaceStatus;
		public virtual string ReplaceStatus
		{
			get
			{
				return this.m_replaceStatus;
			}
			set
			{
				this.m_replaceStatus = value;
			}
		}
		
		private string m_standardType;
		public virtual string StandardType
		{
			get
			{
				return this.m_standardType;
			}
			set
			{
				this.m_standardType = value;
			}
		}
		
		private decimal? m_excessiveRatio;
		public virtual decimal? ExcessiveRatio
		{
			get
			{
				return this.m_excessiveRatio;
			}
			set
			{
				this.m_excessiveRatio = value;
			}
		}
		
		private bool? m_enableOrNot;
		public virtual bool? EnableOrNot
		{
			get
			{
				return this.m_enableOrNot;
			}
			set
			{
				this.m_enableOrNot = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private string m_rowStatus;
		public virtual string RowStatus
		{
			get
			{
				return this.m_rowStatus;
			}
			set
			{
				this.m_rowStatus = value;
			}
		}
		
		private DateTime? m_addDate;
		public virtual DateTime? AddDate
		{
			get
			{
				return this.m_addDate;
			}
			set
			{
				this.m_addDate = value;
			}
		}
		
		private string m_addUserGuid;
		public virtual string AddUserGuid
		{
			get
			{
				return this.m_addUserGuid;
			}
			set
			{
				this.m_addUserGuid = value;
			}
		}
		
		private string m_addUserName;
		public virtual string AddUserName
		{
			get
			{
				return this.m_addUserName;
			}
			set
			{
				this.m_addUserName = value;
			}
		}
		
		private string m_addOUGuid;
		public virtual string AddOUGuid
		{
			get
			{
				return this.m_addOUGuid;
			}
			set
			{
				this.m_addOUGuid = value;
			}
		}
		
		private string m_addOUName;
		public virtual string AddOUName
		{
			get
			{
				return this.m_addOUName;
			}
			set
			{
				this.m_addOUName = value;
			}
		}
		
	}
}
#pragma warning restore 1591
