#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.BaseData;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class MonitoringInstrumentEntity : IMPInfoEntityProperty
	{
		private string m_monitoringinstrumentUid;
		public virtual string MonitoringinstrumentUid
		{
			get
			{
				return this.m_monitoringinstrumentUid;
			}
			set
			{
				this.m_monitoringinstrumentUid = value;
			}
		}
		
		private string m_instrumentUid;
		public virtual string InstrumentUid
		{
			get
			{
				return this.m_instrumentUid;
			}
			set
			{
				this.m_instrumentUid = value;
			}
		}
		
		private string m_acquisitionUid;
		public virtual string AcquisitionUid
		{
			get
			{
				return this.m_acquisitionUid;
			}
			set
			{
				this.m_acquisitionUid = value;
			}
		}
		
		private int? m_fetchDataTime;
		public virtual int? FetchDataTime
		{
			get
			{
				return this.m_fetchDataTime;
			}
			set
			{
				this.m_fetchDataTime = value;
			}
		}
		
		private string m_supportInterfaces;
		public virtual string SupportInterfaces
		{
			get
			{
				return this.m_supportInterfaces;
			}
			set
			{
				this.m_supportInterfaces = value;
			}
		}
		
		private string m_useInterfaces;
		public virtual string UseInterfaces
		{
			get
			{
				return this.m_useInterfaces;
			}
			set
			{
				this.m_useInterfaces = value;
			}
		}
		
		private string m_serialSetting;
		public virtual string SerialSetting
		{
			get
			{
				return this.m_serialSetting;
			}
			set
			{
				this.m_serialSetting = value;
			}
		}
		
		private int? m_serialPort;
		public virtual int? SerialPort
		{
			get
			{
				return this.m_serialPort;
			}
			set
			{
				this.m_serialPort = value;
			}
		}
		
		private int? m_warrantyPeriod;
		public virtual int? WarrantyPeriod
		{
			get
			{
				return this.m_warrantyPeriod;
			}
			set
			{
				this.m_warrantyPeriod = value;
			}
		}
		
		private string m_socketIP;
		public virtual string SocketIP
		{
			get
			{
				return this.m_socketIP;
			}
			set
			{
				this.m_socketIP = value;
			}
		}
		
		private int? m_socketPort;
		public virtual int? SocketPort
		{
			get
			{
				return this.m_socketPort;
			}
			set
			{
				this.m_socketPort = value;
			}
		}
		
		private string m_instrumentNumber;
		public virtual string InstrumentNumber
		{
			get
			{
				return this.m_instrumentNumber;
			}
			set
			{
				this.m_instrumentNumber = value;
			}
		}
		
		private string m_serialNum;
		public virtual string SerialNum
		{
			get
			{
				return this.m_serialNum;
			}
			set
			{
				this.m_serialNum = value;
			}
		}
		
		private string m_socketProtocol;
		public virtual string SocketProtocol
		{
			get
			{
				return this.m_socketProtocol;
			}
			set
			{
				this.m_socketProtocol = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
	}
}
#pragma warning restore 1591
