#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.BaseData;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class MonitoringPointExtensionForEQMSWaterEntity : IMPInfoEntityProperty
	{
		private string m_monitoringPointUid;
		public virtual string MonitoringPointUid
		{
			get
			{
				return this.m_monitoringPointUid;
			}
			set
			{
				this.m_monitoringPointUid = value;
			}
		}
		
		private string m_flowPath;
		public virtual string FlowPath
		{
			get
			{
				return this.m_flowPath;
			}
			set
			{
				this.m_flowPath = value;
			}
		}
		
		private int? m_dataCycle;
		public virtual int? DataCycle
		{
			get
			{
				return this.m_dataCycle;
			}
			set
			{
				this.m_dataCycle = value;
			}
		}
		
		private string m_valley;
		public virtual string Valley
		{
			get
			{
				return this.m_valley;
			}
			set
			{
				this.m_valley = value;
			}
		}
		
		private string m_watersName;
		public virtual string WatersName
		{
			get
			{
				return this.m_watersName;
			}
			set
			{
				this.m_watersName = value;
			}
		}
		
		private decimal? m_stationHouseArea;
		public virtual decimal? StationHouseArea
		{
			get
			{
				return this.m_stationHouseArea;
			}
			set
			{
				this.m_stationHouseArea = value;
			}
		}
		
		private decimal? m_area;
		public virtual decimal? Area
		{
			get
			{
				return this.m_area;
			}
			set
			{
				this.m_area = value;
			}
		}
		
		private string m_samplingMode;
		public virtual string SamplingMode
		{
			get
			{
				return this.m_samplingMode;
			}
			set
			{
				this.m_samplingMode = value;
			}
		}
		
		private DateTime? m_runDatetime;
		public virtual DateTime? RunDatetime
		{
			get
			{
				return this.m_runDatetime;
			}
			set
			{
				this.m_runDatetime = value;
			}
		}
		
		private decimal? m_waterPortShoreDistance;
		public virtual decimal? WaterPortShoreDistance
		{
			get
			{
				return this.m_waterPortShoreDistance;
			}
			set
			{
				this.m_waterPortShoreDistance = value;
			}
		}
		
		private decimal? m_waterPortHouseDistance;
		public virtual decimal? WaterPortHouseDistance
		{
			get
			{
				return this.m_waterPortHouseDistance;
			}
			set
			{
				this.m_waterPortHouseDistance = value;
			}
		}
		
		private string m_factorList;
		public virtual string FactorList
		{
			get
			{
				return this.m_factorList;
			}
			set
			{
				this.m_factorList = value;
			}
		}
		
		private string m_evaluateFactorList;
		public virtual string EvaluateFactorList
		{
			get
			{
				return this.m_evaluateFactorList;
			}
			set
			{
				this.m_evaluateFactorList = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private string m_eQIUid;
		public virtual string EQIUid
		{
			get
			{
				return this.m_eQIUid;
			}
			set
			{
				this.m_eQIUid = value;
			}
		}
		
		private string m_calEQITypeUid;
		public virtual string CalEQITypeUid
		{
			get
			{
				return this.m_calEQITypeUid;
			}
			set
			{
				this.m_calEQITypeUid = value;
			}
		}
		
		private MonitoringPointEntity m_monitoringPointEntity;
		public virtual MonitoringPointEntity MonitoringPointEntity
		{
			get
			{
				return this.m_monitoringPointEntity;
			}
			set
			{
				this.m_monitoringPointEntity = value;
			}
		}
		
	}
}
#pragma warning restore 1591
