#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.BaseData;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class NotifyGradeEntity : IAlarmNotifyEntityProperty
	{
		private string m_notifyGradeUid;
		public virtual string NotifyGradeUid
		{
			get
			{
				return this.m_notifyGradeUid;
			}
			set
			{
				this.m_notifyGradeUid = value;
			}
		}
		
		private string m_gradeUid;
		public virtual string GradeUid
		{
			get
			{
				return this.m_gradeUid;
			}
			set
			{
				this.m_gradeUid = value;
			}
		}
		
		private string m_notifyTypeUid;
		public virtual string NotifyTypeUid
		{
			get
			{
				return this.m_notifyTypeUid;
			}
			set
			{
				this.m_notifyTypeUid = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private GradeEntity m_gradeEntity;
		public virtual GradeEntity GradeEntity
		{
			get
			{
				return this.m_gradeEntity;
			}
			set
			{
				this.m_gradeEntity = value;
			}
		}
		
		private NotifyTypeEntity m_notifyTypeEntity;
		public virtual NotifyTypeEntity NotifyTypeEntity
		{
			get
			{
				return this.m_notifyTypeEntity;
			}
			set
			{
				this.m_notifyTypeEntity = value;
			}
		}
		
	}
}
#pragma warning restore 1591
