#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.BaseData;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class PersonalizedSettingEntity : IBasicInfoEntityProperty
	{
		private string m_personalizedSettingUid;
		public virtual string PersonalizedSettingUid
		{
			get
			{
				return this.m_personalizedSettingUid;
			}
			set
			{
				this.m_personalizedSettingUid = value;
			}
		}
		
		private string m_applicationUid;
		public virtual string ApplicationUid
		{
			get
			{
				return this.m_applicationUid;
			}
			set
			{
				this.m_applicationUid = value;
			}
		}
		
		private string m_userUid;
		public virtual string UserUid
		{
			get
			{
				return this.m_userUid;
			}
			set
			{
				this.m_userUid = value;
			}
		}
		
		private string m_parameterUid;
		public virtual string ParameterUid
		{
			get
			{
				return this.m_parameterUid;
			}
			set
			{
				this.m_parameterUid = value;
			}
		}
		
		private string m_parameterType;
		public virtual string ParameterType
		{
			get
			{
				return this.m_parameterType;
			}
			set
			{
				this.m_parameterType = value;
			}
		}
		
		private bool? m_enableCustomOrNot;
		public virtual bool? EnableCustomOrNot
		{
			get
			{
				return this.m_enableCustomOrNot;
			}
			set
			{
				this.m_enableCustomOrNot = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
	}
}
#pragma warning restore 1591
