#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.BaseData;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class V_Factor_UserConfigEntity : IMPInfoEntityProperty
	{
		private string m_userGuid;
		public virtual string UserGuid
		{
			get
			{
				return this.m_userGuid;
			}
			set
			{
				this.m_userGuid = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private string m_unit;
		public virtual string Unit
		{
			get
			{
				return this.m_unit;
			}
			set
			{
				this.m_unit = value;
			}
		}
		
		private string m_sourceTypeUid;
		public virtual string SourceTypeUid
		{
			get
			{
				return this.m_sourceTypeUid;
			}
			set
			{
				this.m_sourceTypeUid = value;
			}
		}
		
		private string m_sourceType;
		public virtual string SourceType
		{
			get
			{
				return this.m_sourceType;
			}
			set
			{
				this.m_sourceType = value;
			}
		}
		
		private string m_pollutantUid;
		public virtual string PollutantUid
		{
			get
			{
				return this.m_pollutantUid;
			}
			set
			{
				this.m_pollutantUid = value;
			}
		}
		
		private string m_pollutantName;
		public virtual string PollutantName
		{
			get
			{
				return this.m_pollutantName;
			}
			set
			{
				this.m_pollutantName = value;
			}
		}
		
		private string m_pollutantCode;
		public virtual string PollutantCode
		{
			get
			{
				return this.m_pollutantCode;
			}
			set
			{
				this.m_pollutantCode = value;
			}
		}
		
		private string m_personalizedSettingUid;
		public virtual string PersonalizedSettingUid
		{
			get
			{
				return this.m_personalizedSettingUid;
			}
			set
			{
				this.m_personalizedSettingUid = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_measureUnitUid;
		public virtual string MeasureUnitUid
		{
			get
			{
				return this.m_measureUnitUid;
			}
			set
			{
				this.m_measureUnitUid = value;
			}
		}
		
		private string m_loginID;
		public virtual string LoginID
		{
			get
			{
				return this.m_loginID;
			}
			set
			{
				this.m_loginID = value;
			}
		}
		
		private bool? m_isUseOrNot;
		public virtual bool? IsUseOrNot
		{
			get
			{
				return this.m_isUseOrNot;
			}
			set
			{
				this.m_isUseOrNot = value;
			}
		}
		
		private string m_indicatorUid;
		public virtual string IndicatorUid
		{
			get
			{
				return this.m_indicatorUid;
			}
			set
			{
				this.m_indicatorUid = value;
			}
		}
		
		private string m_indicator;
		public virtual string Indicator
		{
			get
			{
				return this.m_indicator;
			}
			set
			{
				this.m_indicator = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private int? m_decimalDigit;
		public virtual int? DecimalDigit
		{
			get
			{
				return this.m_decimalDigit;
			}
			set
			{
				this.m_decimalDigit = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_channelTypeUid;
		public virtual string ChannelTypeUid
		{
			get
			{
				return this.m_channelTypeUid;
			}
			set
			{
				this.m_channelTypeUid = value;
			}
		}
		
		private string m_channelType;
		public virtual string ChannelType
		{
			get
			{
				return this.m_channelType;
			}
			set
			{
				this.m_channelType = value;
			}
		}
		
		private string m_categoryUid;
		public virtual string CategoryUid
		{
			get
			{
				return this.m_categoryUid;
			}
			set
			{
				this.m_categoryUid = value;
			}
		}
		
		private string m_category;
		public virtual string Category
		{
			get
			{
				return this.m_category;
			}
			set
			{
				this.m_category = value;
			}
		}
		
		private string m_applicationUid;
		public virtual string ApplicationUid
		{
			get
			{
				return this.m_applicationUid;
			}
			set
			{
				this.m_applicationUid = value;
			}
		}
		
	}
}
#pragma warning restore 1591
