#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.MonitoringBusiness;

namespace SmartEP.DomainModel.MonitoringBusiness	
{
	public partial class DutyEntity : IMonitoringBusinessEntityProperty
	{
		private Guid m_dutyId;
		public virtual Guid DutyId
		{
			get
			{
				return this.m_dutyId;
			}
			set
			{
				this.m_dutyId = value;
			}
		}
		
		private DateTime? m_dateTime;
		public virtual DateTime? DateTime
		{
			get
			{
				return this.m_dateTime;
			}
			set
			{
				this.m_dateTime = value;
			}
		}
		
		private int? m_pointId;
		public virtual int? PointId
		{
			get
			{
				return this.m_pointId;
			}
			set
			{
				this.m_pointId = value;
			}
		}
		
		private string m_pointName;
		public virtual string PointName
		{
			get
			{
				return this.m_pointName;
			}
			set
			{
				this.m_pointName = value;
			}
		}
		
		private string m_comSituation;
		public virtual string ComSituation
		{
			get
			{
				return this.m_comSituation;
			}
			set
			{
				this.m_comSituation = value;
			}
		}
		
		private string m_datAcquisitionStatus;
		public virtual string DatAcquisitionStatus
		{
			get
			{
				return this.m_datAcquisitionStatus;
			}
			set
			{
				this.m_datAcquisitionStatus = value;
			}
		}
		
		private string m_instrumentCase;
		public virtual string InstrumentCase
		{
			get
			{
				return this.m_instrumentCase;
			}
			set
			{
				this.m_instrumentCase = value;
			}
		}
		
		private string m_systemRunStatus;
		public virtual string SystemRunStatus
		{
			get
			{
				return this.m_systemRunStatus;
			}
			set
			{
				this.m_systemRunStatus = value;
			}
		}
		
		private string m_dutyMan;
		public virtual string DutyMan
		{
			get
			{
				return this.m_dutyMan;
			}
			set
			{
				this.m_dutyMan = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private DateTime? m_addDate;
		public virtual DateTime? AddDate
		{
			get
			{
				return this.m_addDate;
			}
			set
			{
				this.m_addDate = value;
			}
		}
		
		private string m_addUserGuid;
		public virtual string AddUserGuid
		{
			get
			{
				return this.m_addUserGuid;
			}
			set
			{
				this.m_addUserGuid = value;
			}
		}
		
		private string m_addUserName;
		public virtual string AddUserName
		{
			get
			{
				return this.m_addUserName;
			}
			set
			{
				this.m_addUserName = value;
			}
		}
		
		private string m_addOUGuid;
		public virtual string AddOUGuid
		{
			get
			{
				return this.m_addOUGuid;
			}
			set
			{
				this.m_addOUGuid = value;
			}
		}
		
		private string m_addOUName;
		public virtual string AddOUName
		{
			get
			{
				return this.m_addOUName;
			}
			set
			{
				this.m_addOUName = value;
			}
		}
		
		private string m_rowStatus;
		public virtual string RowStatus
		{
			get
			{
				return this.m_rowStatus;
			}
			set
			{
				this.m_rowStatus = value;
			}
		}
		
		private string m_taskCode;
		public virtual string TaskCode
		{
			get
			{
				return this.m_taskCode;
			}
			set
			{
				this.m_taskCode = value;
			}
		}
		
	}
}
#pragma warning restore 1591
