#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace BaseDataModel	
{
	public partial class TB_CreatAlarm
	{
		private string _alarmUid;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		[System.ComponentModel.DataAnnotations.Required()]
		[System.ComponentModel.DataAnnotations.Key()]
		public virtual string AlarmUid
		{
			get
			{
				return this._alarmUid;
			}
			set
			{
				this._alarmUid = value;
			}
		}
		
		private string _applicationUid;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string ApplicationUid
		{
			get
			{
				return this._applicationUid;
			}
			set
			{
				this._applicationUid = value;
			}
		}
		
		private string _monitoringPointUid;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		public virtual string MonitoringPointUid
		{
			get
			{
				return this._monitoringPointUid;
			}
			set
			{
				this._monitoringPointUid = value;
			}
		}
		
		private DateTime? _recordDateTime;
		[System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
		public virtual DateTime? RecordDateTime
		{
			get
			{
				return this._recordDateTime;
			}
			set
			{
				this._recordDateTime = value;
			}
		}
		
		private string _alarmSourceUid;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		public virtual string AlarmSourceUid
		{
			get
			{
				return this._alarmSourceUid;
			}
			set
			{
				this._alarmSourceUid = value;
			}
		}
		
		private string _alarmEventUid;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		public virtual string AlarmEventUid
		{
			get
			{
				return this._alarmEventUid;
			}
			set
			{
				this._alarmEventUid = value;
			}
		}
		
		private string _alarmGradeUid;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		public virtual string AlarmGradeUid
		{
			get
			{
				return this._alarmGradeUid;
			}
			set
			{
				this._alarmGradeUid = value;
			}
		}
		
		private string _dataTypeUid;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		public virtual string DataTypeUid
		{
			get
			{
				return this._dataTypeUid;
			}
			set
			{
				this._dataTypeUid = value;
			}
		}
		
		private string _content;
		[System.ComponentModel.DataAnnotations.StringLength(2000)]
		public virtual string Content
		{
			get
			{
				return this._content;
			}
			set
			{
				this._content = value;
			}
		}
		
		private string _itemCode;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		public virtual string ItemCode
		{
			get
			{
				return this._itemCode;
			}
			set
			{
				this._itemCode = value;
			}
		}
		
		private string _itemName;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		public virtual string ItemName
		{
			get
			{
				return this._itemName;
			}
			set
			{
				this._itemName = value;
			}
		}
		
		private string _itemValue;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		public virtual string ItemValue
		{
			get
			{
				return this._itemValue;
			}
			set
			{
				this._itemValue = value;
			}
		}
		
		private int? _orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this._orderByNum;
			}
			set
			{
				this._orderByNum = value;
			}
		}
		
		private string _description;
		[System.ComponentModel.DataAnnotations.StringLength(500)]
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private string _creatUser;
		[System.ComponentModel.DataAnnotations.StringLength(10)]
		public virtual string CreatUser
		{
			get
			{
				return this._creatUser;
			}
			set
			{
				this._creatUser = value;
			}
		}
		
		private DateTime? _creatDateTime;
		[System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this._creatDateTime;
			}
			set
			{
				this._creatDateTime = value;
			}
		}
		
		private string _updateUser;
		[System.ComponentModel.DataAnnotations.StringLength(10)]
		public virtual string UpdateUser
		{
			get
			{
				return this._updateUser;
			}
			set
			{
				this._updateUser = value;
			}
		}
		
		private DateTime? _updateDateTime;
		[System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this._updateDateTime;
			}
			set
			{
				this._updateDateTime = value;
			}
		}
		
		private bool? _dealFlag;
		public virtual bool? DealFlag
		{
			get
			{
				return this._dealFlag;
			}
			set
			{
				this._dealFlag = value;
			}
		}
		
		private string _dealMan;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		public virtual string DealMan
		{
			get
			{
				return this._dealMan;
			}
			set
			{
				this._dealMan = value;
			}
		}
		
		private DateTime? _dealTime;
		[System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
		public virtual DateTime? DealTime
		{
			get
			{
				return this._dealTime;
			}
			set
			{
				this._dealTime = value;
			}
		}
		
		private string _dealContent;
		[System.ComponentModel.DataAnnotations.StringLength(2000)]
		public virtual string DealContent
		{
			get
			{
				return this._dealContent;
			}
			set
			{
				this._dealContent = value;
			}
		}
		
		private bool? _auditFlag;
		public virtual bool? AuditFlag
		{
			get
			{
				return this._auditFlag;
			}
			set
			{
				this._auditFlag = value;
			}
		}
		
		private string _auditMan;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		public virtual string AuditMan
		{
			get
			{
				return this._auditMan;
			}
			set
			{
				this._auditMan = value;
			}
		}
		
		private DateTime? _auditTime;
		[System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
		public virtual DateTime? AuditTime
		{
			get
			{
				return this._auditTime;
			}
			set
			{
				this._auditTime = value;
			}
		}
		
		private string _auditContent;
		[System.ComponentModel.DataAnnotations.StringLength(2000)]
		public virtual string AuditContent
		{
			get
			{
				return this._auditContent;
			}
			set
			{
				this._auditContent = value;
			}
		}
		
		private string _sendContent;
		[System.ComponentModel.DataAnnotations.StringLength(2000)]
		public virtual string SendContent
		{
			get
			{
				return this._sendContent;
			}
			set
			{
				this._sendContent = value;
			}
		}
		
		private string _monitoringPoint;
		[System.ComponentModel.DataAnnotations.StringLength(50)]
		public virtual string MonitoringPoint
		{
			get
			{
				return this._monitoringPoint;
			}
			set
			{
				this._monitoringPoint = value;
			}
		}
		
	}
}
#pragma warning restore 1591
