#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.MonitoringBusiness;

namespace SmartEP.DomainModel.MonitoringBusiness	
{
	public partial class ScrappedEntity : IMonitoringBusinessEntityProperty
	{
		private string m_scrappedInstrumentUid;
		public virtual string ScrappedInstrumentUid
		{
			get
			{
				return this.m_scrappedInstrumentUid;
			}
			set
			{
				this.m_scrappedInstrumentUid = value;
			}
		}
		
		private string m_instrumentUid;
		public virtual string InstrumentUid
		{
			get
			{
				return this.m_instrumentUid;
			}
			set
			{
				this.m_instrumentUid = value;
			}
		}
		
		private string m_instrumentName;
		public virtual string InstrumentName
		{
			get
			{
				return this.m_instrumentName;
			}
			set
			{
				this.m_instrumentName = value;
			}
		}
		
		private string m_scrappedReason;
		public virtual string ScrappedReason
		{
			get
			{
				return this.m_scrappedReason;
			}
			set
			{
				this.m_scrappedReason = value;
			}
		}
		
		private DateTime? m_scrappedTime;
		public virtual DateTime? ScrappedTime
		{
			get
			{
				return this.m_scrappedTime;
			}
			set
			{
				this.m_scrappedTime = value;
			}
		}
		
		private string m_submitter;
		public virtual string Submitter
		{
			get
			{
				return this.m_submitter;
			}
			set
			{
				this.m_submitter = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private string m_pointName;
		public virtual string PointName
		{
			get
			{
				return this.m_pointName;
			}
			set
			{
				this.m_pointName = value;
			}
		}
		
		private string m_pointId;
		public virtual string PointId
		{
			get
			{
				return this.m_pointId;
			}
			set
			{
				this.m_pointId = value;
			}
		}
		
		private string m_taskCode;
		public virtual string TaskCode
		{
			get
			{
				return this.m_taskCode;
			}
			set
			{
				this.m_taskCode = value;
			}
		}
		
		private int? m_pointType;
		public virtual int? PointType
		{
			get
			{
				return this.m_pointType;
			}
			set
			{
				this.m_pointType = value;
			}
		}
		
		private int? m_infoType;
		public virtual int? InfoType
		{
			get
			{
				return this.m_infoType;
			}
			set
			{
				this.m_infoType = value;
			}
		}
		
	}
}
#pragma warning restore 1591
