#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.AirAutoMonitoring;

namespace SmartEP.DomainModel.AirAutoMonitoring	
{
	public partial class AirCalibrationEntity : IAirAutoMonitoringEntityProperty
	{
		private string m_calibrationGuid;
		public virtual string CalibrationGuid
		{
			get
			{
				return this.m_calibrationGuid;
			}
			set
			{
				this.m_calibrationGuid = value;
			}
		}
		
		private int? m_pointId;
		public virtual int? PointId
		{
			get
			{
				return this.m_pointId;
			}
			set
			{
				this.m_pointId = value;
			}
		}
		
		private DateTime? m_receiveTime;
		public virtual DateTime? ReceiveTime
		{
			get
			{
				return this.m_receiveTime;
			}
			set
			{
				this.m_receiveTime = value;
			}
		}
		
		private DateTime? m_calTime;
		public virtual DateTime? CalTime
		{
			get
			{
				return this.m_calTime;
			}
			set
			{
				this.m_calTime = value;
			}
		}
		
		private DateTime? m_persistentTime;
		public virtual DateTime? PersistentTime
		{
			get
			{
				return this.m_persistentTime;
			}
			set
			{
				this.m_persistentTime = value;
			}
		}
		
		private DateTime? m_intervalTime;
		public virtual DateTime? IntervalTime
		{
			get
			{
				return this.m_intervalTime;
			}
			set
			{
				this.m_intervalTime = value;
			}
		}
		
		private DateTime? m_validTime;
		public virtual DateTime? ValidTime
		{
			get
			{
				return this.m_validTime;
			}
			set
			{
				this.m_validTime = value;
			}
		}
		
		private DateTime? m_endTime;
		public virtual DateTime? EndTime
		{
			get
			{
				return this.m_endTime;
			}
			set
			{
				this.m_endTime = value;
			}
		}
		
		private string m_calNameCode;
		public virtual string CalNameCode
		{
			get
			{
				return this.m_calNameCode;
			}
			set
			{
				this.m_calNameCode = value;
			}
		}
		
		private string m_calTypeCode;
		public virtual string CalTypeCode
		{
			get
			{
				return this.m_calTypeCode;
			}
			set
			{
				this.m_calTypeCode = value;
			}
		}
		
		private string m_calConc;
		public virtual string CalConc
		{
			get
			{
				return this.m_calConc;
			}
			set
			{
				this.m_calConc = value;
			}
		}
		
		private string m_calFlow;
		public virtual string CalFlow
		{
			get
			{
				return this.m_calFlow;
			}
			set
			{
				this.m_calFlow = value;
			}
		}
		
		private string m_calControl;
		public virtual string CalControl
		{
			get
			{
				return this.m_calControl;
			}
			set
			{
				this.m_calControl = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
	}
}
#pragma warning restore 1591
