#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel;

namespace SmartEP.DomainModel	
{
	public partial class V_CodeMainItemEntity : IFrameInfoEntity
	{
		private string m_typeName;
		public virtual string TypeName
		{
			get
			{
				return this.m_typeName;
			}
			set
			{
				this.m_typeName = value;
			}
		}
		
		private string m_typeGuid;
		public virtual string TypeGuid
		{
			get
			{
				return this.m_typeGuid;
			}
			set
			{
				this.m_typeGuid = value;
			}
		}
		
		private int? m_sortNumber;
		public virtual int? SortNumber
		{
			get
			{
				return this.m_sortNumber;
			}
			set
			{
				this.m_sortNumber = value;
			}
		}
		
		private string m_mainGuid;
		public virtual string MainGuid
		{
			get
			{
				return this.m_mainGuid;
			}
			set
			{
				this.m_mainGuid = value;
			}
		}
		
		private string m_itemValue;
		public virtual string ItemValue
		{
			get
			{
				return this.m_itemValue;
			}
			set
			{
				this.m_itemValue = value;
			}
		}
		
		private string m_itemText;
		public virtual string ItemText
		{
			get
			{
				return this.m_itemText;
			}
			set
			{
				this.m_itemText = value;
			}
		}
		
		private string m_itemGuid;
		public virtual string ItemGuid
		{
			get
			{
				return this.m_itemGuid;
			}
			set
			{
				this.m_itemGuid = value;
			}
		}
		
		private string m_itemCode;
		public virtual string ItemCode
		{
			get
			{
				return this.m_itemCode;
			}
			set
			{
				this.m_itemCode = value;
			}
		}
		
		private string m_codeName;
		public virtual string CodeName
		{
			get
			{
				return this.m_codeName;
			}
			set
			{
				this.m_codeName = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
	}
}
#pragma warning restore 1591
