#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.MonitoringBusiness;

namespace SmartEP.DomainModel.MonitoringBusiness	
{
	public partial class AQIForcastDescEntity : IMonitoringBusinessEntityProperty
	{
		private string m_aQIForcastDescUid;
		public virtual string AQIForcastDescUid
		{
			get
			{
				return this.m_aQIForcastDescUid;
			}
			set
			{
				this.m_aQIForcastDescUid = value;
			}
		}
		
		private string m_aQIForcastUid;
		public virtual string AQIForcastUid
		{
			get
			{
				return this.m_aQIForcastUid;
			}
			set
			{
				this.m_aQIForcastUid = value;
			}
		}
		
		private DateTime? m_reportDateTime;
		public virtual DateTime? ReportDateTime
		{
			get
			{
				return this.m_reportDateTime;
			}
			set
			{
				this.m_reportDateTime = value;
			}
		}
		
		private string m_forcastTimeUid;
		public virtual string ForcastTimeUid
		{
			get
			{
				return this.m_forcastTimeUid;
			}
			set
			{
				this.m_forcastTimeUid = value;
			}
		}
		
		private string m_aQIRange;
		public virtual string AQIRange
		{
			get
			{
				return this.m_aQIRange;
			}
			set
			{
				this.m_aQIRange = value;
			}
		}
		
		private string m_primaryPollutant;
		public virtual string PrimaryPollutant
		{
			get
			{
				return this.m_primaryPollutant;
			}
			set
			{
				this.m_primaryPollutant = value;
			}
		}
		
		private string m_class;
		public virtual string Class
		{
			get
			{
				return this.m_class;
			}
			set
			{
				this.m_class = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private AQIForcastEntity m_aQIForcastEntity;
		public virtual AQIForcastEntity AQIForcastEntity
		{
			get
			{
				return this.m_aQIForcastEntity;
			}
			set
			{
				this.m_aQIForcastEntity = value;
			}
		}
		
	}
}
#pragma warning restore 1591
