//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadTreeList {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadTreeList.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add record 的本地化字符串。
        /// </summary>
        internal static string AddRecordText {
            get {
                return ResourceManager.GetString("AddRecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page size: 的本地化字符串。
        /// </summary>
        internal static string ChangePageSizeLabelText {
            get {
                return ResourceManager.GetString("ChangePageSizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change 的本地化字符串。
        /// </summary>
        internal static string ChangePageSizeLinkButtonText {
            get {
                return ResourceManager.GetString("ChangePageSizeLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width: &lt;strong&gt;{0}&lt;/strong&gt; &lt;em&gt;pixels&lt;/em&gt; 的本地化字符串。
        /// </summary>
        internal static string ColumnResizeTooltipFormatString {
            get {
                return ResourceManager.GetString("ColumnResizeTooltipFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag to reorder 的本地化字符串。
        /// </summary>
        internal static string DragToReorder {
            get {
                return ResourceManager.GetString("DragToReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag to resize 的本地化字符串。
        /// </summary>
        internal static string DragToResize {
            get {
                return ResourceManager.GetString("DragToResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop here to reorder 的本地化字符串。
        /// </summary>
        internal static string DropHereToReorder {
            get {
                return ResourceManager.GetString("DropHereToReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First Page 的本地化字符串。
        /// </summary>
        internal static string FirstPageToolTip {
            get {
                return ResourceManager.GetString("FirstPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page: 的本地化字符串。
        /// </summary>
        internal static string GoToPageLabelText {
            get {
                return ResourceManager.GetString("GoToPageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go 的本地化字符串。
        /// </summary>
        internal static string GoToPageLinkButtonText {
            get {
                return ResourceManager.GetString("GoToPageLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        internal static string InsertText {
            get {
                return ResourceManager.GetString("InsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Page 的本地化字符串。
        /// </summary>
        internal static string LastPageToolTip {
            get {
                return ResourceManager.GetString("LastPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Page 的本地化字符串。
        /// </summary>
        internal static string NextPageToolTip {
            get {
                return ResourceManager.GetString("NextPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No records to display. 的本地化字符串。
        /// </summary>
        internal static string NoRecordsText {
            get {
                return ResourceManager.GetString("NoRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of {0} 的本地化字符串。
        /// </summary>
        internal static string PageOfLabelText {
            get {
                return ResourceManager.GetString("PageOfLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decrease 的本地化字符串。
        /// </summary>
        internal static string PageSliderDecreaseToolTip {
            get {
                return ResourceManager.GetString("PageSliderDecreaseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag 的本地化字符串。
        /// </summary>
        internal static string PageSliderDragToolTip {
            get {
                return ResourceManager.GetString("PageSliderDragToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Increase 的本地化字符串。
        /// </summary>
        internal static string PageSliderIncreaseToolTip {
            get {
                return ResourceManager.GetString("PageSliderIncreaseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page &lt;strong&gt;{0}&lt;/strong&gt; of &lt;strong&gt;{1}&lt;/strong&gt; 的本地化字符串。
        /// </summary>
        internal static string PageSliderPagerLabel {
            get {
                return ResourceManager.GetString("PageSliderPagerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Page 的本地化字符串。
        /// </summary>
        internal static string PrevPageToolTip {
            get {
                return ResourceManager.GetString("PrevPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please do not remove this key. 的本地化字符串。
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorted asc 的本地化字符串。
        /// </summary>
        internal static string SortedAscToolTip {
            get {
                return ResourceManager.GetString("SortedAscToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorted desc 的本地化字符串。
        /// </summary>
        internal static string SortedDescToolTip {
            get {
                return ResourceManager.GetString("SortedDescToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to sort 的本地化字符串。
        /// </summary>
        internal static string SortToolTip {
            get {
                return ResourceManager.GetString("SortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
    }
}
