#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.MonitoringBusiness;

namespace SmartEP.DomainModel.MonitoringBusiness	
{
	public partial class OM_TaskItemDatumEntity : IMonitoringBusinessEntityProperty
	{
		private Guid m_rowGuid;
		public virtual Guid RowGuid
		{
			get
			{
				return this.m_rowGuid;
			}
			set
			{
				this.m_rowGuid = value;
			}
		}
		
		private int? m_taskGuid;
		public virtual int? TaskGuid
		{
			get
			{
				return this.m_taskGuid;
			}
			set
			{
				this.m_taskGuid = value;
			}
		}
		
		private string m_taskCode;
		public virtual string TaskCode
		{
			get
			{
				return this.m_taskCode;
			}
			set
			{
				this.m_taskCode = value;
			}
		}
		
		private Guid? m_taskItemGuid;
		public virtual Guid? TaskItemGuid
		{
			get
			{
				return this.m_taskItemGuid;
			}
			set
			{
				this.m_taskItemGuid = value;
			}
		}
		
		private string m_itemValue;
		public virtual string ItemValue
		{
			get
			{
				return this.m_itemValue;
			}
			set
			{
				this.m_itemValue = value;
			}
		}
		
		private DateTime m_itemRecordDate;
		public virtual DateTime ItemRecordDate
		{
			get
			{
				return this.m_itemRecordDate;
			}
			set
			{
				this.m_itemRecordDate = value;
			}
		}
		
		private string m_maintainceUser;
		public virtual string MaintainceUser
		{
			get
			{
				return this.m_maintainceUser;
			}
			set
			{
				this.m_maintainceUser = value;
			}
		}
		
		private DateTime? m_maintainceDate;
		public virtual DateTime? MaintainceDate
		{
			get
			{
				return this.m_maintainceDate;
			}
			set
			{
				this.m_maintainceDate = value;
			}
		}
		
		private string m_remark;
		public virtual string Remark
		{
			get
			{
				return this.m_remark;
			}
			set
			{
				this.m_remark = value;
			}
		}
		
		private string m_itemFactor;
		public virtual string ItemFactor
		{
			get
			{
				return this.m_itemFactor;
			}
			set
			{
				this.m_itemFactor = value;
			}
		}
		
		private string m_itemChildName;
		public virtual string ItemChildName
		{
			get
			{
				return this.m_itemChildName;
			}
			set
			{
				this.m_itemChildName = value;
			}
		}
		
		private string m_universalValue1;
		public virtual string UniversalValue1
		{
			get
			{
				return this.m_universalValue1;
			}
			set
			{
				this.m_universalValue1 = value;
			}
		}
		
		private string m_universalValue2;
		public virtual string UniversalValue2
		{
			get
			{
				return this.m_universalValue2;
			}
			set
			{
				this.m_universalValue2 = value;
			}
		}
		
		private string m_universalValue3;
		public virtual string UniversalValue3
		{
			get
			{
				return this.m_universalValue3;
			}
			set
			{
				this.m_universalValue3 = value;
			}
		}
		
		private string m_universalValue4;
		public virtual string UniversalValue4
		{
			get
			{
				return this.m_universalValue4;
			}
			set
			{
				this.m_universalValue4 = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
	}
}
#pragma warning restore 1591
