#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.AirMonitoringBusiness;

namespace SmartEP.DomainModel.AirMonitoringBusiness	
{
	public partial class AQIForcastConsultationSheetEntity : IAirMonitoringBusinessEntityProperty
	{
		private string m_consultationSheetUid;
		public virtual string ConsultationSheetUid
		{
			get
			{
				return this.m_consultationSheetUid;
			}
			set
			{
				this.m_consultationSheetUid = value;
			}
		}
		
		private DateTime? m_consulDateTime;
		public virtual DateTime? ConsulDateTime
		{
			get
			{
				return this.m_consulDateTime;
			}
			set
			{
				this.m_consulDateTime = value;
			}
		}
		
		private string m_serialText;
		public virtual string SerialText
		{
			get
			{
				return this.m_serialText;
			}
			set
			{
				this.m_serialText = value;
			}
		}
		
		private int? m_serialNo;
		public virtual int? SerialNo
		{
			get
			{
				return this.m_serialNo;
			}
			set
			{
				this.m_serialNo = value;
			}
		}
		
		private string m_currentAQIClass;
		public virtual string CurrentAQIClass
		{
			get
			{
				return this.m_currentAQIClass;
			}
			set
			{
				this.m_currentAQIClass = value;
			}
		}
		
		private string m_currentWeather;
		public virtual string CurrentWeather
		{
			get
			{
				return this.m_currentWeather;
			}
			set
			{
				this.m_currentWeather = value;
			}
		}
		
		private string m_futurePollution;
		public virtual string FuturePollution
		{
			get
			{
				return this.m_futurePollution;
			}
			set
			{
				this.m_futurePollution = value;
			}
		}
		
		private string m_futureAQIClass;
		public virtual string FutureAQIClass
		{
			get
			{
				return this.m_futureAQIClass;
			}
			set
			{
				this.m_futureAQIClass = value;
			}
		}
		
		private string m_futureWeather;
		public virtual string FutureWeather
		{
			get
			{
				return this.m_futureWeather;
			}
			set
			{
				this.m_futureWeather = value;
			}
		}
		
		private string m_takeWarning;
		public virtual string TakeWarning
		{
			get
			{
				return this.m_takeWarning;
			}
			set
			{
				this.m_takeWarning = value;
			}
		}
		
		private string m_issuedUnit;
		public virtual string IssuedUnit
		{
			get
			{
				return this.m_issuedUnit;
			}
			set
			{
				this.m_issuedUnit = value;
			}
		}
		
		private DateTime? m_issuedDateTime;
		public virtual DateTime? IssuedDateTime
		{
			get
			{
				return this.m_issuedDateTime;
			}
			set
			{
				this.m_issuedDateTime = value;
			}
		}
		
		private bool? m_isIssuedOrNot;
		public virtual bool? IsIssuedOrNot
		{
			get
			{
				return this.m_isIssuedOrNot;
			}
			set
			{
				this.m_isIssuedOrNot = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
	}
}
#pragma warning restore 1591
