#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.BaseData;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class EQIEntity : IStandardEntityProperty
	{
		private int m_id;
		public virtual int Id
		{
			get
			{
				return this.m_id;
			}
			set
			{
				this.m_id = value;
			}
		}
		
		private string m_rowGuid;
		public virtual string RowGuid
		{
			get
			{
				return this.m_rowGuid;
			}
			set
			{
				this.m_rowGuid = value;
			}
		}
		
		private string m_eQIUid;
		public virtual string EQIUid
		{
			get
			{
				return this.m_eQIUid;
			}
			set
			{
				this.m_eQIUid = value;
			}
		}
		
		private string m_applicationUid;
		public virtual string ApplicationUid
		{
			get
			{
				return this.m_applicationUid;
			}
			set
			{
				this.m_applicationUid = value;
			}
		}
		
		private string m_range;
		public virtual string Range
		{
			get
			{
				return this.m_range;
			}
			set
			{
				this.m_range = value;
			}
		}
		
		private int? m_iEQI;
		public virtual int? IEQI
		{
			get
			{
				return this.m_iEQI;
			}
			set
			{
				this.m_iEQI = value;
			}
		}
		
		private string m_grade;
		public virtual string Grade
		{
			get
			{
				return this.m_grade;
			}
			set
			{
				this.m_grade = value;
			}
		}
		
		private string m_class;
		public virtual string Class
		{
			get
			{
				return this.m_class;
			}
			set
			{
				this.m_class = value;
			}
		}
		
		private string m_color;
		public virtual string Color
		{
			get
			{
				return this.m_color;
			}
			set
			{
				this.m_color = value;
			}
		}
		
		private string m_rGBValue;
		public virtual string RGBValue
		{
			get
			{
				return this.m_rGBValue;
			}
			set
			{
				this.m_rGBValue = value;
			}
		}
		
		private string m_cMYKValue;
		public virtual string CMYKValue
		{
			get
			{
				return this.m_cMYKValue;
			}
			set
			{
				this.m_cMYKValue = value;
			}
		}
		
		private string m_picturePath;
		public virtual string PicturePath
		{
			get
			{
				return this.m_picturePath;
			}
			set
			{
				this.m_picturePath = value;
			}
		}
		
		private string m_healthEffect;
		public virtual string HealthEffect
		{
			get
			{
				return this.m_healthEffect;
			}
			set
			{
				this.m_healthEffect = value;
			}
		}
		
		private string m_takeStep;
		public virtual string TakeStep
		{
			get
			{
				return this.m_takeStep;
			}
			set
			{
				this.m_takeStep = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private int? m_rowStatus;
		public virtual int? RowStatus
		{
			get
			{
				return this.m_rowStatus;
			}
			set
			{
				this.m_rowStatus = value;
			}
		}
		
		private DateTime? m_addDate;
		public virtual DateTime? AddDate
		{
			get
			{
				return this.m_addDate;
			}
			set
			{
				this.m_addDate = value;
			}
		}
		
		private string m_addUserGuid;
		public virtual string AddUserGuid
		{
			get
			{
				return this.m_addUserGuid;
			}
			set
			{
				this.m_addUserGuid = value;
			}
		}
		
		private string m_addUserName;
		public virtual string AddUserName
		{
			get
			{
				return this.m_addUserName;
			}
			set
			{
				this.m_addUserName = value;
			}
		}
		
		private string m_addOUGuid;
		public virtual string AddOUGuid
		{
			get
			{
				return this.m_addOUGuid;
			}
			set
			{
				this.m_addOUGuid = value;
			}
		}
		
		private string m_addOUName;
		public virtual string AddOUName
		{
			get
			{
				return this.m_addOUName;
			}
			set
			{
				this.m_addOUName = value;
			}
		}
		
		private IList<EQIConcentrationLimitEntity> m_eQIConcentrationLimitEntities = new List<EQIConcentrationLimitEntity>();
		public virtual IList<EQIConcentrationLimitEntity> EQIConcentrationLimitEntities
		{
			get
			{
				return this.m_eQIConcentrationLimitEntities;
			}
		}
		
	}
}
#pragma warning restore 1591
