#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.BaseData;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class InstrumentEntity : IMPInfoEntityProperty
	{
		private int m_id;
		public virtual int Id
		{
			get
			{
				return this.m_id;
			}
			set
			{
				this.m_id = value;
			}
		}
		
		private string m_instrumentName;
		public virtual string InstrumentName
		{
			get
			{
				return this.m_instrumentName;
			}
			set
			{
				this.m_instrumentName = value;
			}
		}
		
		private string m_applyTypeUid;
		public virtual string ApplyTypeUid
		{
			get
			{
				return this.m_applyTypeUid;
			}
			set
			{
				this.m_applyTypeUid = value;
			}
		}
		
		private string m_businessTypeUid;
		public virtual string BusinessTypeUid
		{
			get
			{
				return this.m_businessTypeUid;
			}
			set
			{
				this.m_businessTypeUid = value;
			}
		}
		
		private string m_instrumentTypeUid;
		public virtual string InstrumentTypeUid
		{
			get
			{
				return this.m_instrumentTypeUid;
			}
			set
			{
				this.m_instrumentTypeUid = value;
			}
		}
		
		private string m_brand;
		public virtual string Brand
		{
			get
			{
				return this.m_brand;
			}
			set
			{
				this.m_brand = value;
			}
		}
		
		private string m_factory;
		public virtual string Factory
		{
			get
			{
				return this.m_factory;
			}
			set
			{
				this.m_factory = value;
			}
		}
		
		private string m_producePlace;
		public virtual string ProducePlace
		{
			get
			{
				return this.m_producePlace;
			}
			set
			{
				this.m_producePlace = value;
			}
		}
		
		private string m_supplier;
		public virtual string Supplier
		{
			get
			{
				return this.m_supplier;
			}
			set
			{
				this.m_supplier = value;
			}
		}
		
		private string m_productNumber;
		public virtual string ProductNumber
		{
			get
			{
				return this.m_productNumber;
			}
			set
			{
				this.m_productNumber = value;
			}
		}
		
		private decimal? m_referencePrice;
		public virtual decimal? ReferencePrice
		{
			get
			{
				return this.m_referencePrice;
			}
			set
			{
				this.m_referencePrice = value;
			}
		}
		
		private string m_useConditions;
		public virtual string UseConditions
		{
			get
			{
				return this.m_useConditions;
			}
			set
			{
				this.m_useConditions = value;
			}
		}
		
		private string m_measuringRange;
		public virtual string MeasuringRange
		{
			get
			{
				return this.m_measuringRange;
			}
			set
			{
				this.m_measuringRange = value;
			}
		}
		
		private string m_nicetyRate;
		public virtual string NicetyRate
		{
			get
			{
				return this.m_nicetyRate;
			}
			set
			{
				this.m_nicetyRate = value;
			}
		}
		
		private string m_controlMeasures;
		public virtual string ControlMeasures
		{
			get
			{
				return this.m_controlMeasures;
			}
			set
			{
				this.m_controlMeasures = value;
			}
		}
		
		private string m_useMethod;
		public virtual string UseMethod
		{
			get
			{
				return this.m_useMethod;
			}
			set
			{
				this.m_useMethod = value;
			}
		}
		
		private decimal? m_maintenanceCyc;
		public virtual decimal? MaintenanceCyc
		{
			get
			{
				return this.m_maintenanceCyc;
			}
			set
			{
				this.m_maintenanceCyc = value;
			}
		}
		
		private string m_maintenanceContent;
		public virtual string MaintenanceContent
		{
			get
			{
				return this.m_maintenanceContent;
			}
			set
			{
				this.m_maintenanceContent = value;
			}
		}
		
		private decimal? m_inspectPeriod;
		public virtual decimal? InspectPeriod
		{
			get
			{
				return this.m_inspectPeriod;
			}
			set
			{
				this.m_inspectPeriod = value;
			}
		}
		
		private string m_inspectMethod;
		public virtual string InspectMethod
		{
			get
			{
				return this.m_inspectMethod;
			}
			set
			{
				this.m_inspectMethod = value;
			}
		}
		
		private decimal? m_originCyc;
		public virtual decimal? OriginCyc
		{
			get
			{
				return this.m_originCyc;
			}
			set
			{
				this.m_originCyc = value;
			}
		}
		
		private string m_originTypeUid;
		public virtual string OriginTypeUid
		{
			get
			{
				return this.m_originTypeUid;
			}
			set
			{
				this.m_originTypeUid = value;
			}
		}
		
		private string m_originUnit;
		public virtual string OriginUnit
		{
			get
			{
				return this.m_originUnit;
			}
			set
			{
				this.m_originUnit = value;
			}
		}
		
		private string m_introduction;
		public virtual string Introduction
		{
			get
			{
				return this.m_introduction;
			}
			set
			{
				this.m_introduction = value;
			}
		}
		
		private string m_techniqueParameters;
		public virtual string TechniqueParameters
		{
			get
			{
				return this.m_techniqueParameters;
			}
			set
			{
				this.m_techniqueParameters = value;
			}
		}
		
		private string m_keyFeatures;
		public virtual string KeyFeatures
		{
			get
			{
				return this.m_keyFeatures;
			}
			set
			{
				this.m_keyFeatures = value;
			}
		}
		
		private string m_attachmentUid;
		public virtual string AttachmentUid
		{
			get
			{
				return this.m_attachmentUid;
			}
			set
			{
				this.m_attachmentUid = value;
			}
		}
		
		private string m_instructionPaper;
		public virtual string InstructionPaper
		{
			get
			{
				return this.m_instructionPaper;
			}
			set
			{
				this.m_instructionPaper = value;
			}
		}
		
		private string m_instructionSoft;
		public virtual string InstructionSoft
		{
			get
			{
				return this.m_instructionSoft;
			}
			set
			{
				this.m_instructionSoft = value;
			}
		}
		
		private string m_qualifiedCertificate;
		public virtual string QualifiedCertificate
		{
			get
			{
				return this.m_qualifiedCertificate;
			}
			set
			{
				this.m_qualifiedCertificate = value;
			}
		}
		
		private string m_packingBill;
		public virtual string PackingBill
		{
			get
			{
				return this.m_packingBill;
			}
			set
			{
				this.m_packingBill = value;
			}
		}
		
		private int? m_yearsRange;
		public virtual int? YearsRange
		{
			get
			{
				return this.m_yearsRange;
			}
			set
			{
				this.m_yearsRange = value;
			}
		}
		
		private string m_guarantee;
		public virtual string Guarantee
		{
			get
			{
				return this.m_guarantee;
			}
			set
			{
				this.m_guarantee = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private string m_rowStatus1;
		public virtual string RowStatus1
		{
			get
			{
				return this.m_rowStatus1;
			}
			set
			{
				this.m_rowStatus1 = value;
			}
		}
		
		private string m_rowStatus;
		public virtual string RowStatus
		{
			get
			{
				return this.m_rowStatus;
			}
			set
			{
				this.m_rowStatus = value;
			}
		}
		
		private string m_rowGuid;
		public virtual string RowGuid
		{
			get
			{
				return this.m_rowGuid;
			}
			set
			{
				this.m_rowGuid = value;
			}
		}
		
		private string m_addUserName;
		public virtual string AddUserName
		{
			get
			{
				return this.m_addUserName;
			}
			set
			{
				this.m_addUserName = value;
			}
		}
		
		private string m_addUserGuid;
		public virtual string AddUserGuid
		{
			get
			{
				return this.m_addUserGuid;
			}
			set
			{
				this.m_addUserGuid = value;
			}
		}
		
		private string m_addOUName;
		public virtual string AddOUName
		{
			get
			{
				return this.m_addOUName;
			}
			set
			{
				this.m_addOUName = value;
			}
		}
		
		private string m_addOUGuid;
		public virtual string AddOUGuid
		{
			get
			{
				return this.m_addOUGuid;
			}
			set
			{
				this.m_addOUGuid = value;
			}
		}
		
		private DateTime? m_addDate;
		public virtual DateTime? AddDate
		{
			get
			{
				return this.m_addDate;
			}
			set
			{
				this.m_addDate = value;
			}
		}
		
	}
}
#pragma warning restore 1591
