#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.BaseData;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class MonitoringPointExtensionForEQMSAirEntity : IMPInfoEntityProperty
	{
		private string m_monitoringPointUid;
		public virtual string MonitoringPointUid
		{
			get
			{
				return this.m_monitoringPointUid;
			}
			set
			{
				this.m_monitoringPointUid = value;
			}
		}
		
		private bool? m_calAQIOrNot;
		public virtual bool? CalAQIOrNot
		{
			get
			{
				return this.m_calAQIOrNot;
			}
			set
			{
				this.m_calAQIOrNot = value;
			}
		}
		
		private bool? m_calRegionAQIOrNot;
		public virtual bool? CalRegionAQIOrNot
		{
			get
			{
				return this.m_calRegionAQIOrNot;
			}
			set
			{
				this.m_calRegionAQIOrNot = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private bool? m_superOrNot;
		public virtual bool? SuperOrNot
		{
			get
			{
				return this.m_superOrNot;
			}
			set
			{
				this.m_superOrNot = value;
			}
		}
		
		private bool? m_modelOrNot;
		public virtual bool? ModelOrNot
		{
			get
			{
				return this.m_modelOrNot;
			}
			set
			{
				this.m_modelOrNot = value;
			}
		}
		
		private string m_regionTypeUid;
		public virtual string RegionTypeUid
		{
			get
			{
				return this.m_regionTypeUid;
			}
			set
			{
				this.m_regionTypeUid = value;
			}
		}
		
		private string m_cityTypeUid;
		public virtual string CityTypeUid
		{
			get
			{
				return this.m_cityTypeUid;
			}
			set
			{
				this.m_cityTypeUid = value;
			}
		}
		
		private string m_stname;
		public virtual string Stname
		{
			get
			{
				return this.m_stname;
			}
			set
			{
				this.m_stname = value;
			}
		}
		
		private int? m_dwcode;
		public virtual int? Dwcode
		{
			get
			{
				return this.m_dwcode;
			}
			set
			{
				this.m_dwcode = value;
			}
		}
		
		private string m_stcode;
		public virtual string Stcode
		{
			get
			{
				return this.m_stcode;
			}
			set
			{
				this.m_stcode = value;
			}
		}
		
		private bool? m_stateUploadOrNot;
		public virtual bool? StateUploadOrNot
		{
			get
			{
				return this.m_stateUploadOrNot;
			}
			set
			{
				this.m_stateUploadOrNot = value;
			}
		}
		
		private bool? m_provincialUploadOrNot;
		public virtual bool? ProvincialUploadOrNot
		{
			get
			{
				return this.m_provincialUploadOrNot;
			}
			set
			{
				this.m_provincialUploadOrNot = value;
			}
		}
		
		private MonitoringPointEntity m_monitoringPointEntity;
		public virtual MonitoringPointEntity MonitoringPointEntity
		{
			get
			{
				return this.m_monitoringPointEntity;
			}
			set
			{
				this.m_monitoringPointEntity = value;
			}
		}
		
	}
}
#pragma warning restore 1591
