#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SmartEP.DomainModel.BaseData;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class V_OfflineSettingEntity : IAlarmNotifyEntityProperty
	{
		private string m_useForUid;
		public virtual string UseForUid
		{
			get
			{
				return this.m_useForUid;
			}
			set
			{
				this.m_useForUid = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private int? m_offLineTimeSpan;
		public virtual int? OffLineTimeSpan
		{
			get
			{
				return this.m_offLineTimeSpan;
			}
			set
			{
				this.m_offLineTimeSpan = value;
			}
		}
		
		private string m_offLineSettingUid;
		public virtual string OffLineSettingUid
		{
			get
			{
				return this.m_offLineSettingUid;
			}
			set
			{
				this.m_offLineSettingUid = value;
			}
		}
		
		private bool? m_notifyOrNot;
		public virtual bool? NotifyOrNot
		{
			get
			{
				return this.m_notifyOrNot;
			}
			set
			{
				this.m_notifyOrNot = value;
			}
		}
		
		private string m_notifyGradeUid;
		public virtual string NotifyGradeUid
		{
			get
			{
				return this.m_notifyGradeUid;
			}
			set
			{
				this.m_notifyGradeUid = value;
			}
		}
		
		private string m_monitoringPointUid;
		public virtual string MonitoringPointUid
		{
			get
			{
				return this.m_monitoringPointUid;
			}
			set
			{
				this.m_monitoringPointUid = value;
			}
		}
		
		private string m_monitoringPointName;
		public virtual string MonitoringPointName
		{
			get
			{
				return this.m_monitoringPointName;
			}
			set
			{
				this.m_monitoringPointName = value;
			}
		}
		
		private bool? m_enableOrNot;
		public virtual bool? EnableOrNot
		{
			get
			{
				return this.m_enableOrNot;
			}
			set
			{
				this.m_enableOrNot = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private string m_applicationUid;
		public virtual string ApplicationUid
		{
			get
			{
				return this.m_applicationUid;
			}
			set
			{
				this.m_applicationUid = value;
			}
		}
		
	}
}
#pragma warning restore 1591
