#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace SmartEP.DomainModel.BaseData	
{
	public partial class V_Point_SiteMap_UserConfig_TypeEntity
	{
		private string m_userGuid;
		public virtual string UserGuid
		{
			get
			{
				return this.m_userGuid;
			}
			set
			{
				this.m_userGuid = value;
			}
		}
		
		private string m_updateUser;
		public virtual string UpdateUser
		{
			get
			{
				return this.m_updateUser;
			}
			set
			{
				this.m_updateUser = value;
			}
		}
		
		private DateTime? m_updateDateTime;
		public virtual DateTime? UpdateDateTime
		{
			get
			{
				return this.m_updateDateTime;
			}
			set
			{
				this.m_updateDateTime = value;
			}
		}
		
		private int? m_pOrder;
		public virtual int? POrder
		{
			get
			{
				return this.m_pOrder;
			}
			set
			{
				this.m_pOrder = value;
			}
		}
		
		private string m_pName;
		public virtual string PName
		{
			get
			{
				return this.m_pName;
			}
			set
			{
				this.m_pName = value;
			}
		}
		
		private int m_pID;
		public virtual int PID
		{
			get
			{
				return this.m_pID;
			}
			set
			{
				this.m_pID = value;
			}
		}
		
		private string m_pGuid;
		public virtual string PGuid
		{
			get
			{
				return this.m_pGuid;
			}
			set
			{
				this.m_pGuid = value;
			}
		}
		
		private int? m_orderByNum;
		public virtual int? OrderByNum
		{
			get
			{
				return this.m_orderByNum;
			}
			set
			{
				this.m_orderByNum = value;
			}
		}
		
		private string m_gID;
		public virtual string GID
		{
			get
			{
				return this.m_gID;
			}
			set
			{
				this.m_gID = value;
			}
		}
		
		private string m_description;
		public virtual string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}
		
		private string m_creatUser;
		public virtual string CreatUser
		{
			get
			{
				return this.m_creatUser;
			}
			set
			{
				this.m_creatUser = value;
			}
		}
		
		private DateTime? m_creatDateTime;
		public virtual DateTime? CreatDateTime
		{
			get
			{
				return this.m_creatDateTime;
			}
			set
			{
				this.m_creatDateTime = value;
			}
		}
		
		private int? m_cOrder;
		public virtual int? COrder
		{
			get
			{
				return this.m_cOrder;
			}
			set
			{
				this.m_cOrder = value;
			}
		}
		
		private string m_cGuid;
		public virtual string CGuid
		{
			get
			{
				return this.m_cGuid;
			}
			set
			{
				this.m_cGuid = value;
			}
		}
		
		private string m_applicationUid;
		public virtual string ApplicationUid
		{
			get
			{
				return this.m_applicationUid;
			}
			set
			{
				this.m_applicationUid = value;
			}
		}
		
	}
}
#pragma warning restore 1591
